* <<<301>>> DISCRETE MATHMATICS
:properties:
:author: Dr. R. Sundareswaran and Dr. N. Padmapriya
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 2 | 4 |

** COURSE OBJECTIVES
- Understand the classical logic, implications and equivalences,
  normal forms and its applications.
- Learn Mathematical Induction.
- Learn the basic concepts in graph theory and prove simple properties.
- Understand the basics of group theory.
- Understand the basics of lattices and Boolean algebra.

{{{unit}}}
|UNIT I | LOGIC AND PROOFS  | 13 |
Propositional Logic - Propositional equivalences - Predicates and
quantifiers - Nested quantifiers - Rules of inference - Introduction
to proofs - Proof methods and strategy - Normal forms - Applications
to switching circuits.

{{{unit}}}
|UNIT II | COMBINATORICS | 11 |
Mathematical induction - Strong induction - The pigeonhole principle -
Recurrence relations - Solving linear recurrence relations using
generating functions - Inclusion and Exclusion Principle and its
applications.

{{{unit}}}
|UNIT III | GRAPHS | 10 |
Graphs - Graph terminology and special types of graphs - Subgraphs -
Matrix representation of graphs and graph isomorphism - Connectivity -
Eulerian and Hamilton graphs.

{{{unit}}}
|UNIT IV | ALGEBRAIC STRUCTURES | 13 |
Algebraic systems - Semi groups and monoids - Groups - Subgroups
Homomorphisms - Normal subgroup and coset - Lagrange’s theorem -
Definitions and examples of Rings and Fields.

{{{unit}}}
|UNIT V | LATTICES AND BOOLEAN ALGEBRA | 13 |
Partial ordering - Posets - Lattices as Posets - Properties of
lattices - Lattices as algebraic systems - Sub lattices - Direct
product and Homomorphism - Distributive and Modular lattices - Boolean
algebra - Stone’s representation Theorem.

\hfill *Total Periods: 60*

** COURSE OUTCOMES
On studying this course, the students will able to:
- Write simple proofs using Propositioal and First-Order Logics (K3)
- Write simple proofs using mathematical induction (K3)
- Prove simple graph properties (K3)
- Explain basic concepts in group theory such as semi groups, monoids and groups (K2)
- Solve problems in partial ordering relations, equivalence relations and lattices (K3)

** TEXT BOOKS
1. Kenneth H. Rosen, ``Discrete Mathematics and its Applications'', Tata
   McGraw Hill Pub. Co. Ltd., New Delhi, 7th Edition, Special Indian
   edition, 2017.
2. Tremblay J. P. and Manohar R., ``Discrete Mathematical Structures
   with Applications to Computer Science'', Tata McGraw Hill
   Pub. Co. Ltd, New Delhi, 30th Reprint, 2011.

** REFERENCES
1. Ralph. P. Grimaldi, ``Discrete and Combinatorial Mathematics: An
   Applied Introduction'', Pearson Education Asia, Delhi, 4th
   Edition, 2007.
2. Thomas Koshy, ``Discrete Mathematics with Applications'', Elsevier
   Publications, 2006.
3. Seymour Lipschutz and Mark Lipson, ``Discrete Mathematics'',
   Schaum's Outlines, Tata McGraw Hill Pub. Co. Ltd., New Delhi, 3rd
   Edition, 2010.
4. C. L. Liu, D. P. Mohapatra, ``Elements of Discrete Mathematics'',
   McGraw Higher Ed., 4th Edition, 2012.
5. John. M. Harris, Jeffry. L. Hirst, Michael. J. Mossinghoff,
   ``Combinatorics and Graph Theory'', Verlag New York, 2008.
