* <<<302>>> DIGITAL PRINCIPLES AND SYSTEM DESIGN
:properties:
:author: Ms. S. Angel Deborah and Mr. K. R. Sarath Chandran
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To have a basic knowledge of the concepts and techniques of machine
  learning.

{{{unit}}}
|Unit I | BOOLEAN ALGEBRA AND LOGIC GATES | 9 |
Number Systems - Arithmetic Operations - Binary Codes- Boolean Algebra and Logic Gates
- Theorems and Properties of Boolean Algebra - Boolean Functions - Canonical and
Standard Forms - Simplification of Boolean Functions using Karnaugh Map - Logic Gates –
NAND and NOR Implementations

{{{unit}}}
|Unit II | COMBINATIONAL LOGIC | 9 |
Combinational Circuits – Analysis and Design Procedures - Binary Adder-Subtractor -
Decimal Adder - Binary Multiplier - Magnitude Comparator - Decoders – Encoders –
Multiplexers - Introduction to HDL – HDL Models of Combinational circuits. 

{{{unit}}}
|Unit III | MEMORY AND PROGRAMMABLE LOGIC | 9 |
RAM – Memory Decoding – Error Detection and Correction - ROM - Programmable Logic
Array – Programmable Array Logic – Sequential Programmable Devices

{{{unit}}}
|Unit IV | SYNCHRONOUS SEQUENTIAL LOGIC | 9 |

Sequential Circuits - Storage Elements: Latches , Flip-Flops - Analysis of Clocked
Sequential Circuits - State Reduction and Assignment - Design Procedure - Registers and
Counters - HDL Models of Sequential Circuits.

{{{unit}}}
|Unit V | ASYNCHRONOUS SEQUENTIAL LOGIC | 9 |

Analysis and Design of Asynchronous Sequential Circuits – Reduction of State and Flow
Tables – Race-free State Assignment – Hazards.

\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
      
** References
1. Stephen Marsland, ``Machine Learning – An Algorithmic Perspective'', Second Edition, Chapman and Hall/CRC Machine Learning and Pattern Recognition Series, 2014.
