* <<<303>>> DATA STRUCTURES
:properties:
:author: Ms. M. Saritha and Dr. B. Prabavathy
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To understand the concepts of ADT
- To comprehend the notion of linear and non linear data structures
- To design a suitable data structure for the given problem and
  implement them in a high level programming language
- To understand the need for different types of searching and sorting
  techniques
- To learn the introductory concepts of hashing techniques

{{{unit}}}
|Unit I | Linear Data Structure - List | 9 |
Algorithm analysis: Running time calculations; Abstract Data Types (ADTs); List ADT: array implementation –
linked list implementation – circular linked lists - doubly-linked lists; Applications of lists: polynomial
manipulation.

{{{unit}}}
|Unit II | Linear Data Structures – Stacks and queues | 9 |
Stack ADT – operations; Applications: balancing the symbols,
conversion of infix to postfix expression, evaluating arithmetic
expressions; Queue ADT – operations - circular queue – double ended
queue; Applications of queues.

{{{unit}}}
|Unit III | Non Linear Data Structures – Trees   | 9 |
Tree ADT – preliminaries - tree traversals; Binary Tree ADT –
expression trees; Binary Search Tree ADT - AVL Trees – 
B-Tree – Binary heaps; Applications of trees.
# It is heavy. Do we need splay trees, b-tree

{{{unit}}}
|Unit IV | Non Linear Data Structures – Graphs | 9 |
Definitions – Representation of graph – Types of graph - Breadth-first
traversal – Depth first traversal - Topological sort – Shortest-path
algorithms: Dijkstra's algorithm; Biconnectivity; Applications of graphs.

{{{unit}}}
|Unit V | Searching, Sorting and Hashing Techniques  | 9 |
Searching: Linear search – Binary search; Sorting: Bubble sort - Insertion sort -
Selection sort - Shell sort – Merge sort – Quicksort - Complexity analysis of sorting algorithms; 
Hashing: hash functions - separate chaining – open addressing – rehashing.

\hfill *Total: 45 Periods*

** Course Outcomes
After the completion of this course, students will be able to:
- Elucidate the concepts of linear and non linear data structures (K2)
- Elucidate the concept of searching, sorting and hashing techniques (K2)
- Analyze a problem statement, identify possible data structures for
  solving it, and choose and implement an appropriate one within the
  constraints of the problem specification (K4)
- Critically analyze the various sorting algorithms (K2)

      

** Text book
1. M. A. Weiss, ``Data Structures and Algorithm Analysis in C'', Second
   Edition , Pearson Education, 2006


** References
1. A. V. Aho, J. E. Hopcroft, and J. D. Ullman, ``Data Structures and
   Algorithms'', Pearson Education, First Edition Reprint 2003.
2. R. F. Gilberg, B. A. Forouzan, ``Data Structures'', Second Edition,
   Thomson India Edition, 2005.
3. Ellis Horowitz, Sartaj Sahni, Susan Anderson-Freed, ``Fundamentals
   of Data Structures in C'', Second Edition, University Press, 2008
4. S.Sridhar, ``Design and Analysis of Algorithms``, First Edition, Oxford University Press. 2014
5. Byron Gottfried, Jitender Chhabra, ``Programming with C`` (Schaum’s Outlines Series), Mcgraw Hill Higher Ed., 
   III Edition, 2010
