* <<<303>>> DATA STRUCTURES
:properties:
:author: Ms. M. Saritha and Dr. B. Prabavathy
:date: 
:end:

#+BEGIN_COMMENT
include at least one application of trees (?)
#+END_COMMENT

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the concepts of ADT
- To comprehend the notion of linear and non linear data structures
- To design a suitable data structure for the given problem and
  implement them in a high level programming language
- To understand the different types of searching and sorting techniques
- To learn the introductory concepts of hashing techniques

{{{unit}}}
|UNIT I | Linear Data Structures - List | 10 |
Algorithm analysis: Running time calculations; Abstract Data Types (ADTs) - List ADT: Array implementation of lists –
Linked lists – Circular linked lists - Doubly linked lists - Applications of lists: polynomial manipulation.

{{{unit}}}
|UNIT II | Linear Data Structures – Stacks and Queues | 8 |
Stack ADT: Stack model - Implementation of stacks - Applications: Balancing symbols - Infix to postfix conversion -
Evaluating postfix expressions - Queue ADT: Queue model - Array implementation of queues - Applications of queues.

{{{unit}}}
|UNIT III | Non Linear Data Structures – Trees   | 9 |
Trees: Preliminaries - Tree traversals - Binary trees - Expression trees - Binary Search Tree ADT - AVL Trees – 
B-Tree - Applications of trees; Priority queues: Binary heap.

{{{unit}}}
|UNIT IV | Non Linear Data Structures – Graphs | 9 |
Graph algorithms: Definitions – Representation of graphs - Topological sort - Shortest-path
algorithms: Dijkstra's algorithm - All-Pairs shortest path - Breadth-first traversal – Depth-first traversal - Biconnectivity - Applications of graphs.

{{{unit}}}
|UNIT V | Searching, Sorting and Hashing Techniques  | 9 |
Searching: Linear search – Binary search; Sorting: Bubble sort - Insertion sort -
Selection sort - Shell sort; Hashing: Hash function - Separate chaining – Open addressing – Rehashing.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
- Implement linear data structures (K3)
- Implement non linear data structures (K3)
- Elucidate the concept of searching, sorting and hashing techniques (K2)
- Compare searching and sorting algorithms in terms of time and space (K2)
- Analyze a problem statement and choose an appropriate data structure to solve it (K4)

      
** TEXT BOOKS
1. M. A. Weiss, ``Data Structures and Algorithm Analysis in C'', Second
   Edition , Pearson Education, 2006
2. Richard F. Gilberg, Behrouz A. Forouzan, ``Data Structures: A
   Pseudocode Approach with C'', Second Edition, Cengage India, 2007.

** REFERENCES
1. A. V. Aho, J. E. Hopcroft, and J. D. Ullman, ``Data Structures and
   Algorithms'', Pearson Education, First Edition Reprint 2003.
2. R. F. Gilberg, B. A. Forouzan, ``Data Structures'', Second Edition,
   Thomson India Edition, 2005.
3. Ellis Horowitz, Sartaj Sahni, Susan Anderson-Freed, ``Fundamentals
   of Data Structures in C'', Second Edition, University Press, 2008
4. S. Sridhar, ``Design and Analysis of Algorithms``, First Edition, Oxford University Press. 2014
5. Byron Gottfried, Jitender Chhabra, ``Programming with C`` (Schaum’s Outlines Series), Mcgraw Hill Higher Ed., 
   III Edition, 2010
