* <<<305>>> UNIX AND SHELL PROGRAMMING
:properties:
:author: Mr. B. Senthil Kumar and Dr. S. Sheerazuddin
:date: 13 November 2018
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|2|0|2|3|

** Course Objectives
- To learn UNIX Commands
- To learn vi Editor
- To learn File handling in UNIX
- To learn Shell Programming


|Unit I|FOUNDATIONS|5|
Foundations: Why Unix -- Computer System -- The Unix Environment -- UNIX Structure -- UNIX Commands; Basic vi Editor: Editor concepts -- The vi Editor -- Modes and Commands; Local Commands in vi; Range Commands in vi -- Global Commands in vi; Rearrange Text in vi;

|Unit II|FILE SYSTEM|5|
File Systems: Filenames -- File Types -- Regular Files -- Directories -- File System Implementation -- Operations on Files and Directories; Security and File Permissions: Users and Groups -- Security Levels -- Changing Permissions -- User Masks -- Changing Ownership and Groups.

|Unit III|BASH BASICS|6|
bash Basics: What is a shell? -- History of UNIX Shells -- Interactive Shell Use -- Input & Output -- Background Jobs -- Special Characters and Quoting; Command-line Editing: Enabling Command-line Editing -- The History List -- emacs Editing Mode -- emacs Editing Mode -- The fc Command -- Histroy Expansion -- readline; Customizing Your Environment; .bash_profile, .bash_logout, .bashrc Files -- Aliases -- Options -- Shell Variables -- Customization and Subprocesses.

|Unit IV|SHELL PROGRAMMING|6|
Basic Shell Programming: Shell Scripts and Functions -- Shell Variables -- String Operators -- Command Substitution; Flow Control; Command-line Options and Typed Variables: Command-line Options -- Typed Variables -- Integer Variables and Arithmetic -- Arrays.

|Unit V|INPUT/OUTPUT, PROCESS HANDLING AND DEBUGGING|8|
Input/Output and Command-Line Processing: I/O Redirectors -- String I/O -- Command-Line Processing; Process Handling: Process IDs & Job Numbers -- Job Control -- Signals -- trap -- Coroutines -- Subshells -- Process Substitution; Debugging Shell Programs: Basic Debugging Aids -- A bash Debugger.


|Total:|30|

** LIST OF EXPERIMENTS
1. Exercises on basic UNIX commands.
2. Exercises on file and directory handling.
3. Exercises on security and file permissions.
4. Exercises on pipes, quotes, aliases and variables.
5. Exercises on filters.
6. Exercises using sed.
7. Exercises using grep.
8. Exercises using awk.
9. Exercises on C Shell scripting.
10. Exercises on Perl scripting.

\hfill *Total Periods: 30*

** Course Outcomes
After the completion of this course, students will be able to:
- Work in UNIX environment using command line (K2).
- Handle files proficiently (K2).
- Use vi editor with proficiency (K3).
- Work with the bash Shell (K2).
- Write Shell programs (K3).

** TEXTBOOK
1. Behrouz Forouzan and Richard Gilberg “UNIX and Shell Programming: A Textbook” Thomson Learning Inc., 2005 (Units I & II)
2. Cameron Newham and Bill Rosenblatt "Learning the bash Shell", Third Edition, O'Reilly, 2005 (Units III, IV & V)

** REFERENCES
1. Richard Blum and Christine Bresnahan, ``Linux Command Line and Shell Scripting Bible'', Wiley, 2015.
2. Sumitabha Das, ``Unix : Concepts and Applications'', Tata McGraw Hill,2017.
3. Stephen Kochan and Patrick Wood, ``Shell Programming in UNIX, Linux and OSX'', Addison Wesly, 2016.
4. M G Venkateshmurthy , ``Introduction to Unix and Shell Programming'', 1st Edition, Pearson Education, 2005.
5. Randal K Michael ``Mastering Unix Shell Scripting'', 2nd Edition, Wiley, 2008.
