* <<<305>>> UNIX AND SHELL PROGRAMMING
:properties:
:author: Mr. B. Senthil Kumar and Dr. S. Sheerazuddin
:date: 13 November 2018
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|2|0|2|3|

** Course Objectives
- To learn UNIX Commands
- To learn vi Editor
- To learn File handling in UNIX
- To learn Shell Programming.


| Unit I | FOUNDATIONS | 5 |
Foundations: Why Unix -- Computer system -- The Unix environment --
UNIX structure -- UNIX commands; Basic vi Editor: Editor concepts --
The vi Editor -- Modes and commands; Local commands in vi; Range
commands in vi -- Global commands in vi; Rearrange text in vi;

| Unit II | FILE SYSTEM | 5 |
File Systems: Filenames -- File types -- Regular files -- Directories
-- File system implementation -- Operations on files and directories;
Security and File Permissions: Users and groups -- Security levels --
Changing permissions -- User masks -- Changing ownership and groups.

|Unit III|BASH BASICS|6|
Bash Basics: What is a shell? -- History of UNIX shells -- Interactive
shell usage -- Input & output -- Background jobs -- Special characters
and quoting; Command-Line Editing: Enabling command-line editing --
The history list -- emacs editing mode -- emacs editing mode -- The fc
command -- Histroy expansion -- Readline; Customizing your
environment; .bash_profile, .bash_logout, .bashrc Files -- Aliases --
Options -- Shell variables -- Customization and subprocesses.

| Unit IV | SHELL PROGRAMMING | 6 |
Basic Shell Programming: Shell scripts and functions -- Shell
variables -- String operators -- Command substitution; Flow control;
Command-line options and Typed Variables: Command-line options --
Typed variables -- Integer variables and arithmetic -- Arrays.

| Unit V | INPUT/OUTPUT, PROCESS HANDLING AND DEBUGGING | 8 |
Input/Output and Command-Line Processing: I/O redirectors -- String
I/O -- Command-line processing; Process Handling: Process IDs & job
numbers -- Job control -- Signals -- Trap -- Coroutines -- Subshells
-- Process substitution; Debugging Shell Programs: Basic debugging
Aids -- A bash debugger.

\hfill *Total Periods: 30*

** LIST OF EXPERIMENTS
1. Exercises on basic UNIX commands.
2. Exercises on file and directory handling.
3. Exercises on security and file permissions.
4. Exercises on pipes, quotes, aliases and variables.
5. Exercises on filters.
6. Exercises on Shell program debugging.

\hfill *Total Periods: 30*

** Course Outcomes
After the completion of this course, students will be able to:
- Work in UNIX environment using command line (K2)
- Handle files proficiently (K2)
- Use vi editor with proficiency (K3)
- Work with the bash Shell (K2)
- Write Shell programs (K3).

** TEXTBOOK
1. Behrouz Forouzan, Richard Gilberg ``UNIX and Shell Programming:
   A Textbook'', Thomson Learning, 2005 (Units I & II)
2. Cameron Newham, Bill Rosenblatt ``Learning the bash Shell'',
   Third Edition, O'Reilly, 2005 (Units III, IV & V)

** REFERENCES
1. Richard Blum, Christine Bresnahan, ``Linux Command Line and
   Shell Scripting Bible'', Wiley, 2015.
2. Sumitabha Das, ``Unix: Concepts and Applications'', Tata McGraw
   Hill,2017.
3. Stephen Kochan, Patrick Wood, ``Shell Programming in UNIX, Linux
   and OSX'', Addison Wesley, 2016.
4. M G Venkateshmurthy, ``Introduction to Unix and Shell
   Programming'', 1st Edition, Pearson Education, 2005.
5. Randal K Michael, ``Mastering Unix Shell Scripting'', 2nd Edition,
   Wiley, 2008.
