* <<<305>>> UNIX AND SHELL PROGRAMMING
:properties:
:author: Mr. B. Senthil Kumar and Dr. S. Sheerazuddin
:date: 13 November 2018
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 2 | 0 | 2 | 3 |

** COURSE OBJECTIVES
- To learn UNIX Commands
- To learn vi Editor
- To learn the use of Regular Expressions in UNIX
- To learn File handling in UNIX
- To learn Shell Programming

{{{unit}}}
|UNIT I|FOUNDATIONS|9|
Foundations: Why Unix -- Computer System -- The Unix Environment --
UNIX Structure -- UNIX Commands; Basic vi Editor: Editor concepts --
The vi Editor -- Modes and Commands; Local Commands in vi; Range
Commands in vi -- Global Commands in vi; Rearrange Text in vi; ex
Editor; emacs editor.

{{{unit}}}
|UNIT II|FILES & REGULAR EXPRESSIONS|9|
File Systems: Filenames -- File Types -- Regular Files -- Directories
-- File System Implementation -- Operations on Files and Directories;
Security and File Permissions: Users and Groups -- Security Levels --
Changing Permissions -- User Masks -- Changing Ownership and Groups;
Regular Expressions: Atoms -- Operators; grep; sed: Scripts --
Operation -- Addresses -- Commands.

{{{unit}}}
|UNIT III|SHELLS & FILTERS|9|
Introduction to Shells: UNIX Session -- Standard Streams -- Redirection
-- Pipes -- Command Execution -- Command-Line Editing -- Quotes -- Command
Substitution -- Job Control -- Aliases -- Variables -- Options --
Shell/Environment Customization; Filters; Communications: Mail --
Remote Access -- File Transfer; awk: Execution -- Fields & Records --
Operation -- Patterns -- Actions.

{{{unit}}}
|UNIT IV|KORN SHELL|9|
Interactive Korn Shell: Korn Shell Features -- Variables -- Output --
Input -- Exit Status of a Command -- eval Command -- Environment
Variables -- Options -- Startup Scripts -- Command History -- Command
Execution Process; Korn Shell Programming: Basic Script Concepts --
Expressions -- Making Selections -- Repetition -- Special Parameters and
Variables -- shift Command -- Argument Validation -- Debugging Scripts --
Script Examples.

{{{unit}}}
|UNIT V|C SHELL|9|
Interactive C Shell: C Shell Features -- Variables -- Output -- Input --
Exit Status of a Command -- eval Command -- Environment Variables --
On-Off Variables -- Startup and Shutdown Scripts -- Command History --
Command Execution Scripts; C Shell Programming: Basic Script Concepts
-- Expressions -- Making Selections -- Repetition -- Special Parameters --
shift Command -- Argument Validation -- Debugging Scripts -- Script
Examples.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Work in UNIX environment using command line (K2).
- Use vi editor with proficiency (K3).
- Write Shell programs (K3).

** TEXTBOOK
1. Behrouz Forouzan and Richard Gilberg, ``UNIX and Shell Programming: A
   Textbook'', Thomson Learning Inc., 2005

** REFERENCES
1. Richard Blum and Christine Bresnahan, ``Linux Command Line and Shell
   Scripting Bible'', Wiley 2015
2. Sumitabha Das, ``Unix : Concepts and Applications'', Tata McGraw Hill
   2017
3. Stephen Kochan and Patrick Wood, ``Shell Programming in UNIX, Linux
   and OSX'', Addison Wesly 2016
4. M.G. Venkateshmurthy , ``Introduction to Unix and Shell Programming'', 
   Pearson Education; First edition, 2005
5. Randal K. Michael ``Mastering Unix Shell Scripting'',  Wiley; 2nd edition, 2008
