* <<<401>>> PROBABILITY AND STATISTICAL METHODS
:properties:
:author: Dr. G. Kalpana and Dr. N. Padmapriya
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 2 | 0 | 4 |

** Course Objectives
- Identify the standard distributions and apply them in solving problems.
- Understand the concept of two-dimensional random variables and solve
  problems in finding the Joint probabilities and correlation between
  them.
- Perform hypothesis testing using normal, t-distribution and F-distribution.
- Evaluate the tests of significance in analysis of variance.
- Calculate the various statistical quality control measurements. 

{{{unit}}}
|UNIT I| 	RANDOM VARIABLES|           12|
Probability - Axioms of probability - Conditional probability - Baye’s
theorem - Discrete and Continuous random variables - Moments - Moment
generating functions -Binomial, Poisson, Geometric, Uniform,
Exponential, Gamma, Normal distributions- Functions of a random
variable

{{{unit}}}
|UNIT II| 	TWO-DIMENSIONAL RANDOM VARIABLES|      12|
Joint distributions - Marginal and Conditional distributions -
Covariance - Correlation and Linear regression - Transformation of
random variables - Central limit theorem (for independent
andidentically distributed random variables).

{{{unit}}}
| UNIT III | 	TESTS OF SIGNIFICANCE | 12 |
Sampling distributions -Small and large sample test- Test based on
Normal and t distribution (Single and difference of mean and
proportion)- χ2- Test forgoodness of fit, Independence of attributes-
F test for variance.

{{{unit}}}
| UNIT IV | 	DESIGN OF EXPERIMENTS | 12 |
Completely randomized design - Randomized block design - Latin square
design -22 factorialdesign.

{{{unit}}}
|UNIT V| 	STATISTICAL QUALITY CONTROL| 12     |
Control charts for measurements (X and R charts) - Control charts for
attributes (p, c and npcharts) - Tolerance limits - Acceptance
sampling.

\hfill *Total: 60 Hours*

** Course Outcomes
After the completion of this course, students will be able to: 
- Identify standard distributions and apply them.
- Solve problems in two dimension random variables and find the
  correlation between them.
- Identify and apply the suitable testing of hypothesis under normal
  and t and F distribution.
- Solve problems in analysis of variance.
- Analyze quality control by applying control chart methods.
      
** Text Books
1. Milton, J. S. and Arnold, J.C., ``Introduction to Probability and
   Statistics'', Tata McGrawHill, New Delhi, 4th Edition, 3rd
   Reprint, 2008.
2. Johnson, R.A. and Gupta, C.B., ``Miller and Freund's Probability and
   Statistics forEngineers'', Pearson Education, Asia, 8th
   Edition, 2011.

** References
1. Devore, J.L., ``Probability and Statistics for Engineering and the
   Sciences'', ThomsonBrooks/Cole, International Student Edition, New
   Delhi, 7th Edition, 2008.
2. Walpole, R.E., Myers, R.H., Myers, S.L. and Ye, K., ``Probability
   and Statistics forEngineers and Scientists'', Pearson Education,
   Asia, 8th Edition, 2007.
3. Ross, S.M., ``Introduction to Probability and Statistics for
   Engineers and Scientists'', Elsevier, New Delhi, 3rd Edition, 2004.
4. Spiegel, M.R., Schiller, J. and Srinivasan, R.A., ``Schaum’s
   Outline of Theory and Problems of Probability and Statistics'',
   Tata McGraw Hill, New Delhi, 2004.
5. Gupta, S.C and Kapoor, V.K., ``Fundamentals of Mathematical
   Statistics'', Sultan and Chand Company, New Delhi, 2009.
