* <<<402>>> COMPUTER ARCHITECTURE AND ORGANISATION
:properties:
:author: Ms. K. Lekshmi and Dr. D. Venkatavara Prasad
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn the basic structure and operations of a computer. 
- To learn the arithmetic and logic unit and implementation of fixed-point and floating point arithmetic unit. 
- To learn the basics of pipelined execution. 
- To understand parallelism and multi-core processors. 
- To understand the memory hierarchies, cache and virtual memories and communication with I/O devices. 

{{{unit}}}
|UNIT I | BASIC STRUCTURE OF A COMPUTER SYSTEM | 9 |
Functional Units -- Basic Operational Concepts -- Performance;
Instructions: Language of the Computer -- Operations, Operands -- Instruction representation;
Logical operations -- decision making; MIPS Addressing. 

{{{unit}}}
|UNIT II | ARITHMETIC FOR COMPUTERS | 9 |
Addition and Subtraction; Multiplication; Division; Floating Point Representation:
Floating Point Operations; Subword Parallelism.

{{{unit}}}
|UNIT III | PROCESSOR AND CONTROL UNIT | 9 |
A Basic MIPS implementation: Building a Datapath -- Control Implementation Scheme;
Pipelining: Pipelined datapath and control -- Handling Data Hazards & Control Hazards -- Exceptions.

{{{unit}}}
|UNIT IV | MEMORY & I/O SYSTEMS | 9 |
Memory Hierarchy; memory technologies; cache memory: measuring and improving cache performance;
virtual memory: TLB‘s; Accessing I/O Devices -- Interrupts; Direct Memory Access;
Bus structure -- Bus operation -- Arbitration; Interface circuits; USB.

{{{unit}}}
|UNIT V | PARALLEL PROCESSORS | 9 |
Parallel processing challenges; Flynn‘s classification: SISD -- MIMD -- SIMD --SPMD
and Vector Architectures; Hardware multithreading; Multi-core processors and other Shared Memory Multiprocessors;
Introduction to Graphics Processing Units.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the basics structure of computers, operations and instructions. (K2)
- Design arithmetic and logic unit. (K3)
- Understand pipelined execution and design control unit. (K3)
- Design of various memory systems and understand I/O communication. (K3)
- Understand parallel processing architectures. (K2)

** TEXT BOOKS
1. David A. Patterson and John L. Hennessy, ``Computer Organization
   and Design: The Hardware/Software Interface'', Fifth Edition,
   Morgan Kaufmann / Elsevier, 2014. (units I, III, IV, V)
2. Carl Hamacher, Zvonko Vranesic, Safwat Zaky and Naraig Manjikian,
   ``Computer Organization and Embedded Systems'', Sixth Edition, Tata
   McGraw Hill, 2012. (unit II)

** REFERENCES
1. William Stallings, ``Computer Organization and Architecture – Designing for Performance'',
2. Eighth Edition, Pearson Education, 2010. 
3. John P. Hayes, ``Computer Architecture and Organization'', Third Edition, Tata McGraw Hill, 2012. 
4. John L. Hennessey and David A. Patterson, ``Architecture – A Quantitative Approach'', 5th edition,
5. Morgan Kaufmann / Elsevier, 2012. (units I, III). 
6. Morris Mano M, ``Computer System Architecture'', Revised Third Edition, Pearson Publication, 2017.
7. Chakraborty P, ``Computer Architecture and Organization'', JAICO Publishing House, 2010.
