* <<<402>>> COMPUTER ARCHITECTURE
:properties:
:author: Ms. K. Lekshmi and Dr. D. Venkatavara Prasad
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To learn the basic structure and operations of a computer. 
- To learn the arithmetic and logic unit and implementation of fixed-point and floating point arithmetic unit. 
- To learn the basics of pipelined execution. 
- To understand parallelism and multi-core processors. 
- To understand the memory hierarchies, cache memories and virtual memories. 
- To learn the different ways of communication with I/O devices. 

{{{unit}}}
|Unit I | Basi Structure of a Computer System | 9 |
Functional Units -- Basic Operational Concepts -- Performance;
Instructions: Language of the Computer -- Operations, Operands -- Instruction representation;
Logical operations -- decision making; MIPS Addressing. 

{{{unit}}}
|Unit II | Arithmetic for Computers | 9 |
Addition and Subtraction; Multiplication; Division; Floating Point Representation:
Floating Point Operations; Subword Parallelism.

{{{unit}}}
|Unit III | Processor and Control Unit | 9 |
A Basic MIPS implementation: Building a Datapath -- Control Implementation Scheme;
Pipelining: Pipelined datapath and control -- Handling Data Hazards & Control Hazards -- Exceptions.

{{{unit}}}
|Unit IV | Parallelism | Hours |
Parallel processing challenges; Flynn‘s classification: SISD -- MIMD -- SIMD --SPMD
and Vector Architectures; Hardware multithreading; Multi-core processors and other Shared Memory Multiprocessors;
Introduction to Graphics Processing Units; Clusters; Warehouse Scale Computers and other Message-Passing Multiprocessors.

{{{unit}}}
|Unit V | Memory & I/O Systems | Hours |
Memory Hierarchy; memory technologies; cache memory: measuring and improving cache performance;
virtual memory: TLB‘s; Accessing I/O Devices -- Interrupts; Direct Memory Access;
Bus structure -- Bus operation -- Arbitration; Interface circuits; USB.

\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basics structure of computers, operations and instructions. (K2)
- Design arithmetic and logic unit. (K3)
- Understand pipelined execution and design control unit. (K3)
- Understand parallel processing architectures. (K2)
- Understand the design of various memory systems and I/O communication. (K3)

** Text Books
1.  David A. Patterson and John L. Hennessy, ``Computer Organization and Design: The Hardware/Software Interface'', 
	Fifth Edition, Morgan Kaufmann / Elsevier, 2014. (units I, III, IV, V)
2.  Carl Hamacher, Zvonko Vranesic, Safwat Zaky and Naraig Manjikian, ``Computer Organization and Embedded Systems'', 
	Sixth Edition, Tata McGraw Hill, 2012. (unit II)

** References
1.	William Stallings, ``Computer Organization and Architecture – Designing for Performance'',
	Eighth Edition, Pearson Education, 2010. 
2.	John P. Hayes, ``Computer Architecture and Organization'', Third Edition, Tata McGraw Hill, 2012. 
3. John L. Hennessey and David A. Patterson, ``Architecture – A Quantitative Approach'', 5th edition,
   Morgan Kaufmann / Elsevier, 2012. (units I, III). 
