* <<<403>>> OPERATING SYSTEMS
:properties:
:author: Mr. H. Shahul Hamead and Ms. S. Lakshmi Priya
:date: 13-11-2018
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- Understand the structure and functions of OS.
- Learn about Processes, Threads and Scheduling algorithms. 
- Understand the principles of concurrency and Deadlocks. 
- Learn various memory management schemes. 
- Study I/O management and File systems.


{{{unit}}}
|Unit I | Operating Systems Overview | 9 |
Computer System Overview: Basic elements -- Instruction execution – Interrupts -- Memory hierarchy -- Cache memory -- Direct memory access -- Multiprocessor and multicore organization; Operating System Overview: Objectives and functions -- Evolution of operating system;Computer System Organization; Operating System Structure and Operations: System calls -- System programs -- OS generation and system boot.

{{{unit}}}
|Unit II | Process Management | 12 |
Processes: Process concept -- Process scheduling -- Operations on processes -- Interprocess Communication; Threads: Overview --  Multithreading Models -- Thread Issues; Process Synchronization - Critical Section Problem -- Mutex Locks -- Semophores --  Monitors; CPU Scheduling: FCFS, SJF, Priority, Roundrobin, Rate Montonic and EDF scheduling; Deadlocks -- Aviodance -- Prevention -- Detection and Recovery.

{{{unit}}}
|Unit III | Memory Management | 8 |

Main Memory: Contiguous Memory Allocation -- Segmentation -- Paging -- 32 and 64 bit architecture Examples; Virtual Memory: Demand paging -- Page replacement algorithms -- Allocation -- Thrashing;  

{{{unit}}}
|Unit IV | Storage Management | 9 |
Mass Storage Structure: Overview -- Disk scheduling and management; File System Storage: File concepts -- Directory and disk structure -- Sharing and protection; File System Implementation: File system structure -- Directory structure -- Allocation methods -- Free space management -- I/O systems

{{{unit}}}
|Unit V | Case Study | 7 |
Linux Vs Windows: Design principles -- Process management -- Scheduling -- Memory management -- File systems;  
Mobile OS: iOS  and  Android -- Introduction and Architecture. 

\hfill *Total: <45 Hours>*

** Course Outcomes
After the completion of this course, students will be able to: 
- Analyze various Scheduling algorithms (K4) 
- Apply the principles of concurrency (K3)
- Understand deadlock, prevention and avoidance algorithms (K2)
- Compare and contrast various memory management schemes (K2)
- Understand the functionality of file systems (K2)
- Compare and contrast Linux, Windows and mobile operating systems (K2)

** Text Book
1. Abraham Silberschatz, Peter Baer Galvin and Greg Gagne, “Operating System Concepts”, 9 th Edition, John Wiley and Sons Inc., 2012.
2. Neil Smyth, "iPhone iOS 4 Development Essentials - Xcode", Fourth Edition, Payload media,2011.     

** References
1. Ramaz Elmasri, A. Gil Carrick, David Levine, "Operating Systems A Spiral Approach" , Tata McGraw Hill Edition, 2010.
2. Achyut S.Godbole, Atul Kahate,"Operating Systems", McGraw Hill Education, 2016.
3. Andrew S. Tanenbaum, "Modern Operating Systems", Second Edition, Pearson Education, 2004.
4. Gary Nutt, "Operating Systems", Third Edition, Pearson Education, 2004.
5. Harvey M. Deitel, "Operating Systems", Third Edition, Pearson Education, 2004.
6. Daniel P Bovet and Marco Cesati, "Understanding the Linux kernel", 3rd edition, O‘Reilly,2005.
