* <<<404>>> DESIGN AND ANALYSIS OF ALGORITHMS
:properties:
:author: Dr.S.Kavitha and Mr.V.Balasubramanian
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 2 | 4 |

** COURSE OBJECTIVES
- Learn the algorithm analysis techniques
- Become familiar with the different algorithm design techniques
- Understand the limitations of algorithm power.

{{{unit}}}
|UNIT I|INTRODUCTION AND ANALYSIS |10| 
Introduction: Notion of an algorithm -- Fundamentals of algorithmic
Problem solving -- Important problem types; Fundamentals of the
Analysis of Algorithm Efficiency: The Analysis Framework –- Asymptotic
Notations, properties and Basic Efficiency Classes -– Mathematical
analysis for Recursive and Non-recursive algorithms -- Empirical
Analysis of Algorithms -- Algorithm Visualization.

{{{unit}}}
|UNIT II|BRUTE FORCE AND DIVIDE AND CONQUER |8| 
Brute Force and Exhaustive Search: Brute-Force String Matching --
Closest-Pair and Convex-Hull Problems; Exhaustive Search: Traveling
Salesman Problem -- Knapsack Problem -- Assignment problem.  Divide
and conquer: Mergesort –- Quicksort -– Multiplication of Large
Integers and Strassen's Matrix Multiplication -- Closest-Pair and
Convex-Hull Problems.

{{{unit}}}
|UNIT III |DYNAMIC PROGRAMMING AND GREEDY TECHNIQUE |9| 
Dynamic Programming: Computing a Binomial Coefficient -- Knapsack
Problem and Memory functions -- Optimal Binary Search Trees --
Warshall's and Floyd's algorithm.  Greedy Technique: Prim's algorithm
-- Kruskal's Algorithm -- Dijkstra's Algorithm -- Huffman Trees and
codes.

{{{unit}}}
|UNIT IV | ITERATIVE IMPROVEMENT AND BACKTRACKING |9| 
Iterative Improvement: The Simplex Method -- The Maximum-Flow Problem
–- Maximum Matching in Bipartite Graphs -- The Stable marriage Problem;
Backtracking: n-Queens problem –- Hamiltonian Circuit Problem --
Subset Sum Problem.

{{{unit}}}
|UNIT V | BRANCH & BOUND AND LIMITATIONS OF ALGORITHM POWER |9| 
Branch and Bound: Assignment problem -- Knapsack Problem -- Traveling
Salesman Problem; Limitations of Algorithm Power: Lower-Bound
Arguments -- P, NP and NP-Complete Problems; Coping with the
Limitations of Algorithm Power: Approximation Algorithms for NP-Hard
Problems -- Traveling Salesman problem -- Knapsack problem.

\hfill *Theory Periods: 45*

** SUGGESTIVE EXPERIMENTS
1. Implementation of non-recursive and recursive algothms for the given
   problem
2. Implementation of string matching using Brute Force technique
3. Implementation of assignment problem using Exhaustive Search
   technique
4. Implementation of merge sort and quick sort using Divide and
   Conquer technique
5. Implementation of Knapsack Problem using Dynamic Programming
6. Implementation of Huffman Trees and generate its code
8. Implementation of n-Queens problem using Backtracking technique
9. Implementation of Traveling Salesman Problem using Branch and Bound
   technique
10. Mini project

\hfill *Practical Periods: 30*

\hfill *Total Periods: 75*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Design algorithms for various computing problems(K3)
- Analyze the time and space complexity of algorithms(K4)
- Compare the different algorithm design techniques for a given problem(K4)
- Modify existing algorithms to improve efficiency(K4)
- Understand the limitations of algorithmic power(K2)

** TEXT BOOKS
1. Anany Levitin, ``Introduction to the Design and Analysis of
   Algorithms'', 3rd Edition, Pearson Education, 2012.
2. S Dasgupta, C H Papadimitriou, and U V Vazirani,
   ``Algorithms'',1st Edition,  McGraw Hill Education, 2017.

** REFERENCES
1. Thomas H Cormen, Charles E Leiserson, Ronald L Rivest and Clifford
   Stein, ``Introduction to Algorithms'', 3rd Edition, PHI Learning
   Private Limited, 2012
2. Steven S Skiena, ``The Algorithm Design Manual'', 2nd Edition,
   Springer, 2008.

