* <<<406>>> SOFTWARE ENGINEERING
:properties:
:author: Ms. K. Madheswari and Ms. S. Angel Deborah
:date: 
:end:

#+startup: showall

| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To understand the phases in a software project
- To understand fundamental concepts of requirements engineering and Analysis Modeling.
- To understand the various software design methodologies
- To learn various testing and maintenance measures

|Unit I | SOFTWARE PROCESS AND AGILE DEVELOPMENT | 9 |
Introduction to Software Engineering, Software Process, Perspective and Specialized Process
Models –Introduction to Agility-Agile process-Extreme programming-XP Process.


|Unit II | REQUIREMENTS ANALYSIS AND SPECIFICATION  | 9 |
Software Requirements: Functional and Non-Functional, User requirements, System requirements,
Software Requirements Document – Requirement Engineering Process: Feasibility Studies,
Requirements elicitation and analysis, requirements validation, requirements managementClassical
analysis: Structured system Analysis, Petri Nets- Data Dictionary.

|Unit III | SOFTWARE DESIGN | 9 |
Design process – Design Concepts-Design Model– Design Heuristic – Architectural Design -
Architectural styles, Architectural Design, Architectural Mapping using Data Flow- User Interface
Design: Interface analysis, Interface Design –Component level Design: Designing Class based
components, traditional Components.

|Unit IV | TESTING AND MAINTENANCE | 9 |
Software testing fundamentals-Internal and external views of Testing-white box testing - basis
path testing-control structure testing-black box testing- Regression Testing – Unit Testing –
Integration Testing – Validation Testing – System Testing And Debugging –Software
Implementation Techniques: Coding practices-Refactoring-Maintenance and Reengineering-BPR
model-Reengineering process model-Reverse and Forward Engineering.

|Unit V | PROJECT MANAGEMENT | 9 |
Software Project Management: Estimation – LOC, FP Based Estimation, Make/Buy Decision
COCOMO I & II Model – Project Scheduling – Scheduling, Earned Value Analysis Planning –
Project Plan, Planning Process, RFP Risk Management – Identification, Projection - Risk
Management-Risk Identification-RMMM Plan-CASE TOOLS

Total: 45

** Course Outcomes
After the completion of this course, students will be able to: 
- Identify the key activities in managing a software project and choose an appropraite process model(K2).
- Perform requirements engineering and Analysis Modeling(K3).
- Apply systematic procedure for software design and deployment(K3).
- Compare and contrast the various testing and maintenance(K3).
- Manage project schedule, estimate project cost and effort required(K3).
      
** Text Books
1. Roger S. Pressman, "Software Engineering – A Practitioner's Approach", Seventh Edition, Mc
Graw-Hill International Edition, 2010.
2. Ian Sommerville, "Software Engineering", 9th Edition, Pearson Education Asia, 2011.
