* <<<501>>> COMPUTER NETWORKS
:properties:
:author:  Ms. S. V. Jansi Rani and Mr. N. Sujaudeen
:date: 
:date: 12-11-2018
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |
 
** COURSE OBJECTIVES
- To understand the protocol layering and physical level communication.
- To understand the various components required to build different networks.
- To learn the functions of network layer and the various routing protocols.
- To familiarize the functions and protocols of the Transport layer.
- To understand various application layer protocols.

{{{unit}}}
|UNIT I |INTRODUCTION AND PHYSICAL LAYER|9| 	
Introduction: Networks -- Network Types -- Protocol Layering -- TCP/IP
Protocol suite -- OSI Model; Physical Layer: Performance --
Transmission media -- Switching -- Circuit-switched Networks -- Packet
Switching.

{{{unit}}}
|UNIT II | DATE-LINK LAYER AND MEDIA ACCESS | 9 |
Introduction: Link-Layer Addressing -- DLC Services -- Data-Link Layer
Protocols -- HDLC -- PPP -- Media Access Control -- Wired LANs:
Ethernet -- Wireless LANs -- Introduction -- IEEE 802.11 -- Bluetooth
-- Connecting Devices.

{{{unit}}}
|UNIT III | NETWORK LAYER | 9 |
Network Layer Services -- Packet switching -- Performance -- IPV4
Addresses -- Forwarding of IP Packets; Network Layer Protocols: IP --
ICMP v4 -- Unicast Routing Algorithms -- Protocols -- Multicasting
Basics -- IPV6 Addressing -- IPV6 Protocol.

{{{unit}}}
|UNIT IV | TRANSPORT LAYER | 9 |
Introduction: Transport Layer Protocols -- Services -- Port Numbers --
User Datagram Protocol -- Transmission Control Protocol -- SCTP.

{{{unit}}}
|UNIT V | APPLICATION LAYER | 9 |
Traditional applications -Electronic Mail (SMTP, POP3, IMAP, MIME) –
HTTP – File Transfer Protocol - Secure Shell (SSH) - DNS – SNMP.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the principles, design, terminology and concepts of the network models(K2)
- Learn the protocols of data link layer and apply error control mechanisms(K3)
- Understand the core functions of network layer protocols and apply them for data communication(K3)
- Learn the purpose of Transport Layer Protocols such as UDP and TCP(K2)
- Understand the Application Layer Protocols and their basic functionalities(K2)


** TEXT BOOKS 
1. Behrouz A Forouzan, ``Data Communications and Networking'', 5th Edition TMH, 2013.
2. Larry L Peterson, Bruce S Davie, ``Computer Networks: A Systems Approach'', 5th Edition,
 Morgan Kaufmann Publishers Inc., 2012.

** REFERENCES

1. William Stallings, ``Data and Computer Communications'', 10th Edition, Pearson Education, 2013.
2. Nader F Mir, ``Computer and Communication Networks'', 2nd Edition, Prentice Hall, 2014.
3. Ying-Dar Lin, Ren-Hung Hwang and Fred Baker, ``Computer Networks: An Open Source Approach'',
 McGraw Hill Publisher, 2011.
4. James F Kurose, Keith W Ross, ``Computer Networking, A Top-Down Approach Featuring the Internet'', 
6th Edition, Pearson Education, 2013.
5. Andrew S. Tanenbaum, David J Wetherall, ``Computer Networks'', 5th Edition, Pearson Education,2013.
