* <<<503>>> THEORY OF COMPUTATION
:properties:
:author: Ms. A. Beulah 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
The student should be made to: 
- To construct finite automata for any given pattern and find its equivalent regular expressions.
- To understand the language hierarchy  and  to design a context free grammar for any given language.
- To construct pushdown automata  for any CFL.
- To understand Turing machines and their capability.
- To understand undecidable problems.


{{{unit}}}
|Unit I | Finite Automata and Regular Languages  | 10 |
Introduction-Basic Mathematical Notation and techniques- Finite Automata (FA): Deterministic Finite Automata (DFA)– Non-deterministic Finite Automata(NFA) – Finite Automata with Epsilon Transitions- Equivalence of FA’s –Minimization of DFA;  Regular Languages - Regular Expression – Equivalence of finite Automata  and Regular Expressions –  Proving Languages not to be regular – Closure Properties of Regular Languages.


{{{unit}}}
|Unit II | <Title> | <Hours> |

{{{unit}}}
|Unit III | <Title> | <Hours> |

{{{unit}}}
|Unit IV | <Title> | <Hours> |

{{{unit}}}
|Unit V | <Title> | <Hours> |


\hfill *Total: <Total Hours>*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
      
** References
1. Stephen Marsland, ``Machine Learning – An Algorithmic Perspective'', Second Edition, Chapman and Hall/CRC Machine Learning and Pattern Recognition Series, 2014.
