* <<<503>>> THEORY OF COMPUTATION
:properties:
:author: Ms. A. Beulah and Mr. V. Balasubramanian
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To construct finite automata for any given pattern and find its equivalent regular expressions
- To understand the language hierarchy and to design a context free grammar for any given language
- To construct pushdown automata for any CFL
- To understand Turing machines and their capability
- To understand undecidable problems.


{{{unit}}}
|UNIT I | FINITE AUTOMATA AND REGULAR LANGUAGES  | 10 |
Introduction: Basic Mathematical Notation and Techniques; Finite Automata (FA):
 Deterministic Finite Automata (DFA) -- Non-deterministic
Finite Automata(NFA) -- Finite automata with epsilon transitions -- 
Equivalence of FA’s -- Minimization of DFA; Regular Expressions and
Languages: Regular expressions -- Finite automata and regular expressions; 
Properties of Regular Languages: Proving languages not to be regular -- 
Closure and decision properties of regular languages.

{{{unit}}}
|UNIT II | CONTEXT FREE GRAMMARS AND LANGUAGES  | 8 |
Chomsky’s hierarchy of languages; Context-Free Grammar and Languages: Context-Free Grammar (CFG) -- Parse trees -- Ambiguity in grammars and languages; Normal Forms for Context Free Grammars: Eliminating useless symbols -- Computing the generating and reachable symbols -- eliminating null productions -- Eliminating unit productions -- Chomsky Normal Form(CNF) -- Greibach Normal Form (GNF).

{{{unit}}}
|UNIT III | PUSHDOWN AUTOMATA | 9 |
Pushdown Automaton (PDA): Definition of the Pushdown automaton -- The languages of a PDA -- Equivalence of PDAs and CFGs -- Deterministic pushdown automata; Pumping Lemma for Context Free Languages.

{{{unit}}}
|UNIT IV | TURING MACHINES  | 9 |
The Turing Machine -- Programming Techniques for Turing Machines -- Extensions to the Basic Turing Machine -- Restricted Turing Machines.

{{{unit}}}
|UNIT V | UNDECIDABILITY | 9 |
Undecidablity: Language that is not Recursively Enumerable(RE) -- Undecidable problem that is RE -- Undecidable problems about turing machines -- Post's Correspondence Problem (PCP) -- Other undecidable problems.

\hfill *Total Periods: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Construct automata, regular expression for any given pattern (K3)
- Understand the need of formal languages, and grammars (K3)
- Design pushdown automata for any CFL (K3)
- Design Turing machines for any Languages (K3)
- Explain the Decidability or Undecidability of various problems (K2).

** Text Books 
1. Hopcroft J E, Motwani R and Ullman J D, ``Introduction to Automata Theory, Languages and Computations'', Pearson
   Education, 3rd Edition, 2008.

** References
1. Harry R Lewis and Christos H Papadimitriou, ``Elements of the Theory of Computation'', Prentice Hall of India, 2nd Edition,  2003.
2. Peter Linz, ``An Introduction to Formal Language and Automata'', Narosa Publishers, 3rd Edition, 2002.
3. Mishra K L P and Chandrasekaran N, ``Theory of Computer Science -Automata, Languages and Computation'',  Prentice
   Hall of India, 3rd Edition, 2004.
