* <<<503>>> THEORY OF COMPUTATION
:properties:
:author: Ms. A. Beulah and Mr. V. Balasubramanian
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To construct finite automata for any given pattern and find its equivalent regular expressions
- To understand the language hierarchy and to design a context free grammar for any given language
- To construct pushdown automata for any CFL
- To understand Turing machines and their capability
- To understand undecidable problems.

#+begin_comment
1. Each unit is reframed according to the computational models. 
2. For changes, see the individual units, some units were reordered
3. This subject is not offered under M.E syllabus.
4. Five Course outcomes specified and aligned with units.
#+end_comment



{{{unit}}}
|UNIT I | FINITE AUTOMATA AND REGULAR LANGUAGES  | 10 |
Basic Mathematical Notation and Techniques; Finite Automata (FA): Deterministic Finite Automata (DFA) --
 Non-deterministic Finite Automata(NFA) -- Finite automata with epsilon transitions -- Equivalence of FA’s 
-- Minimization of DFA; Regular Expressions and Languages: Regular expressions -- 
Finite automata and regular expressions; Properties of Regular Languages: Proving languages not to be regular
 -- Closure and decision properties of regular languages.
 
 #+begin_comment
AU R-17 Uint I and II are combined together  to a single unit. Unit I is grouped under Finite Automata.
#+end_comment

{{{unit}}}
|UNIT II | CONTEXT FREE GRAMMARS AND LANGUAGES  | 8 |
Chomsky’s Hierarchy of Languages; Context-Free Grammar and Languages: Context-Free Grammar (CFG) --
 Parse trees -- Ambiguity in grammars and languages; Normal Forms for Context Free Grammars:
 Eliminating useless symbols -- Computing the generating and reachable symbols -- 
Eliminating null productions -- Eliminating unit productions -- Chomsky Normal Form(CNF) --
 Greibach Normal Form (GNF).
  #+begin_comment
Few topics of AU R-17 Uint III and IV are combined together  and named as CFG and Languages.
#+end_comment


{{{unit}}}
|UNIT III | PUSHDOWN AUTOMATA | 9 |
Pushdown Automata (PDA): Definition of the Pushdown automaton -- The languages of a PDA -- 
Equivalence of PDAs and CFGs -- Deterministic Pushdown automata; Pumping Lemma for Context Free Languages.

#+begin_comment
Few topics of AU R-17 Uint III is removed and reframed as second computational model (Pushdown Automata).
#+end_comment

{{{unit}}}
|UNIT IV | TURING MACHINES  | 9 |
The Turing Machine -- Programming Techniques for Turing Machines --  Extensions to the Basic Turing Machine -- Restricted Turing Machines.

#+begin_comment
Turing machine in AU R-17 is a part of Uint IV. Now it is reframed as a separate unit with new versions of TM.
#+end_comment

{{{unit}}}
|UNIT V | UNDECIDABILITY | 9 |
Undecidablity: Language that is not Recursively Enumerable(RE) --  Undecidable problem that is RE -- Undecidable problems about turing machines -- Post's Correspondence Problem (PCP) -- Other undecidable problems.

\hfill *Total Periods: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Construct automata, regular expression for any given pattern (K3)
- Understand the need of formal languages, and grammars (K3)
- Design pushdown automata for any CFL (K3)
- Design Turing machines for any Languages (K3)
- Explain the Decidability or Undecidability of various problems (K2).

** Text Books 
1. Hopcroft J E, Motwani R and Ullman J D, ``Introduction to Automata Theory, Languages and Computations'', Pearson
   Education, 3rd Edition, 2008.

** References
1. Harry R Lewis and Christos H Papadimitriou, ``Elements of the Theory of Computation'', Prentice Hall of India, 2nd Edition,  2003.
2. Peter Linz, ``An Introduction to Formal Language and Automata'', Narosa Publishers, 3rd Edition, 2002.
3. Mishra K L P and Chandrasekaran N, ``Theory of Computer Science -Automata, Languages and Computation'',  Prentice
   Hall of India, 3rd Edition, 2004.
