* <<<504>>> INTRODUCTION TO MACHINE LEARNING
:properties:
:author: Ms. S. Rajalakshmi and Ms. M. Saritha
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the need of machine learning techniques for various
  problems.
- To study the various supervised, unsupervised and reinforcement
  learning algorithms in machine learning.
- To study the dimensionality reduction techniques to represent tha data and their
  dependencies.
- To understand the need of optimisation techniques.

{{{unit}}}
|UNIT I | INTRODUCTION  | 8 |
Introduction: Machine Learning -- Examples of Machine Learning
Applications: Learning Associations -- Classification -- Regression --
Unsupervised Learning -- Reinforcement Learning ; Preliminaries: Weight space -- Curse
of dimensionality -- Testing machine learning algorithms -- Turning
data into probabilities -- Basic statistics -- Bias-variance tradeoff.

{{{unit}}}
|UNIT II | SUPERVISED LEARNING  | 11 |
Neural Networks and Linear Discriminants: Brain and the neuron --
Neural networks -- Perceptron -- Linear separability -- Linear
regression; Multi-layer Perceptron: Going forward -- Back-propagation
of error; Support Vector Machines.

{{{unit}}}
|UNIT III | TREE LEARNING AND PROBABILISTIC LEARNING | 9 |
Learning with Trees: Constructing decision trees -- Classification and Regression trees -- 
Classification example ; Ensemble learning: Boosting -- Bagging -- Random forests; 
Probabilistic Learning: Gaussian mixture models -- Nearest neighbour methods.

{{{unit}}}
|UNIT IV | UNSUPERVISED LEARNING AND REINFORCEMENT LEARNING | 9 |
Unsupervised: K-means algorithm -- Self-Organising feature map;
Reinforcement learning: State and action space -- Reward function -- Discounting
-- Action selection -- Policy -- Markov Decision Process -- Values.

{{{unit}}}
|UNIT V | DIMENSIONALITY REDUCTION AND OPTIMISATION TECHNIQUES| 8 |
Dimensionlity Reduction Techniques: Linear Discriminant analysis,
Principal Component Analysis; Optimisation and Search: Least-squares optimisation --
 Conjugate gradients -- Search approaches -- Exploitation and exploration.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
- Apply supervised and unsupervised learning algorithms for different tasks (K3).
- Understand the use of reinforcement learning techniques to various problems (K2).
- Understand the requirement of dimensionality reduction and optimisation techniques (K2).
- Apply and analyze the various machine learning algorithms for real world problems (K4).
      
** TEXT BOOKS
1. Stephen Marsland, ``Machine Learning – An Algorithmic
   Perspective'', 2nd Edition, Chapman and Hall/CRC Machine
   Learning and Pattern Recognition Series, 2015.
2. Ethem Alpaydin, ``Introduction to Machine Learning'', 3rd Edition, The MIT
   Press 2014.


** REFERENCES
1. Jason Bell, ``Machine learning – Hands on for Developers and
   Technical Professionals'', 1st Edition, Wiley, 2014.
2. Peter Flach, ``Machine Learning: The Art and Science of Algorithms
   that Make Sense of Data'', 1st Edition, Cambridge University
   Press, 2012.
3. Richert, Willi, ``Building machine learning systems with Python'',
   Packt Publishing Ltd, 2013.
4. Tom M Mitchell, ``Machine Learning'', McGraw-Hill Education
   (India) Private Limited, 2013.
5. Y S Abu-Mostafa, M Magdon-Ismail, and H T Lin, ``Learning from
   Data'', AMLBook Publishers, 2012.



