* <<<601>>> INTERNET PROGRAMMING 
:properties:
:author: Dr. B. Prabavathy and Dr. V. S. Felix Enigo
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C | 
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand different client and server end technologies
- To develop web application using traditional technologies
- To understand and develop web application using emerging web application frameworks 

{{{unit}}}
|UNIT I | WEB ESSENTIALS | 9 |
Web Essentials: Clients, Servers and Communication – The Internet –
Basic Internet protocols – World wide web – HTTP Request Message –
HTTP Response Message – Web Clients – Web Servers – HTML5: Tables,
Lists, Image, Redefined form elements, Semantic elements, Audio and
video controls - CSS3: Inline, embedded and external style sheets,
Rule cascading, Inheritance, Adding graphics to web pages,
Transformations, Transitions and Animations.


{{{unit}}}
|UNIT II | CLIENT END TECHNOLOGIES | 9 |
Client side programming language – Javascript: Variables, Data types,
Statements, Operators, Objects, Arrays, Built-in objects and Event
handling – DOM: Introduction, Document tree, Node object, Document,
element and text nodes, Event handling, Event propagation.

{{{unit}}}
|UNIT III | SERVER END TECHNOLOGIES| 9 |
Servlets: Architecture, Life Cycle, Parameter data, Sessions, Cookies
and URL rewriting – AJAX: Ajax Client Server Architecture-XML Http
Request Object-Call Back Methods

{{{unit}}}
|UNIT IV | CLIENT END FRAMEWORK | 9 |
Introduction to AngularJS – Directives and Controllers, Data binding
and Models, Form validation, Form controls – Services: Dependency
injection, order of injection – Server communication using $http.


{{{unit}}}
|UNIT V | SERVER END FRAMEWORK | 9 |
Introduction to NodeJS – Event Loop – Patterns – Core APIs:
EventEmitter, Callback syntax, Streams - File system, Buffers –
Process module - Data Access – NoSQL and Document stores: MongoDB.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Design a modern website using HTML5 and CSS3  (K3)
- Design and implement dynamic web pages with JavaScript and DOM (K3)
- Develop web application using Servlet (K3)
- Develop responsive web application using Servlets and AJAX (K3)
- Develop web applications using AngularJS and NodeJS frameworks (K3)
      
** TEXT BOOKS
1. Jeffrey C and Jackson, ``Web Technologies A Computer Science
   Perspective'', Pearson Education, 2011.
2. Matthew MacDonald, ``HTML5: The missing manual'', O'Reilly Media,
   August 2011
3. David McFarland, ``CSS3: The missing manual'', O'Reilly Media,
   December 2012.
4. Brad Green and Shyam Seshadri, ``AngularJS'', O'Reilly Media, Inc.,
   First Edition, 2013.
5. Tom Hughes-Crouchers and Mike Wilson, ``Node: Up and Running'', 1st Edition,
   O'Reilly Media, 2012.
