* <<<702>>> MOBILE COMPUTING
:properties:
:author: Dr. V. S. Felix Enigo and Ms. A. Beulah
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |


** COURSE OBJECTIVES
The student should be made to:
- Understand the basic concepts of mobile computing
- Be familiar with the protocol stack.
- Be exposed to Ad-Hoc networks.
- Learn the basics of mobile telecommunication system.
- Gain knowledge about different mobile platforms and application development environments.

{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Introduction to mobile computing - MAC: Motivation for a specialized
MAC- SDMA – FDMA – TDMA – CDMA – Comparison of S/T/F/CDMA; Wireless
LAN: Infrastructure based and adhoc networks - IEEE 802.11 - Bluetooth

{{{unit}}}
|UNIT II | NETWORK LAYER | 9 |
Mobile IP: Goals, assumptions and requirements - Entities and
terminology - IP packet delivery - Agent discovery -Registration
-Tunneling and Encapsulation – Optimizations; AdHoc: Proactive
protocol-DSDV, Reactive Routing Protocols – DSR, AODV.

{{{unit}}}
| UNIT III | TRANSPORT AND APPLICATION LAYER | 9 |
Traditional TCP – Classical TCP improvements; Wireless Application
Protocol: WAP – Architecture – WDP – WTLS – WTP –WSP – WAE – WML -
WTA.

{{{unit}}}
|UNIT IV | MOBILE TELECOMMUNICATION SYSTEM | 9 |
Introduction - Global System for Mobile Communication (GSM): Mobile
services -System architecture - Radio interface - Localization and
calling - Handover –Security; General Packet Radio Service (GPRS);
Universal Mobile Telecommunication System (UMTS): UMTS architecture -
UTRAN - Core network – Handover.

{{{unit}}}
|UNIT V | MOBILE PLATFORMS AND APPLICATION ENVIRONMENTS | 9 |
iOS: iOs Architecture- iOS Simulator; Android: Platform Architecture-
Developing Android Applications- Anatomy of Android Applications–
Android SDK; Windows Phone: Platform Architecture - Silverlight
Framework; Mobile Web: Being Mobile Friendly - WebKit - Web vs Native
vs Hybrid - Mobile Web Application Frameworks.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Identify the functionalities of datalink layer.(K3)
- Explain the functionalities of mobile network layer and routing in Ad hoc networks.(K3)
- Analyze the transport and application layer protocols.(K3)
- Explain the basics of mobile telecommunication system.(K2)
- Develop a mobile application.(K3)

** TEXT BOOKS
1. Jochen H. Schller, ``Mobile Communications'', Second Edition,
   Pearson Education, New Delhi, 2007. (Unit I -IV)
2. Helal, Sumi, Raja Bose, and Wendong Li. ``Mobile Platforms and
   Development Environments.'' Synthesis Lectures on Mobile and
   Pervasive Computing, 2012. (Unit V))

** REFERENCES
1. Helal, Abdelsalam A., et al. ``Any Time, Anywhere Computing: Mobile
   Computing Concepts and Technology''. Vol. 522. First Edition,
   Springer Science & Business Media, 1999.
2. Dharma Prakash Agarval, Qing and An Zeng, ``Introduction to
   Wireless and Mobile systems'', Third Edition ,Thomson Asia Pvt
   Ltd, 2005.
3. Uwe Hansmann, Lothar Merk, Martin S. Nicklons and Thomas Stober,
   ``Principles of Mobile Computing'', Springer, 2003.
4. William.C.Y.Lee, ``Mobile Cellular Telecommunications--Analog and
   Digital Systems'', Second Edition,Tata Mc Graw Hill Edition ,2006.
5. C.K.Toh, ``AdHoc Mobile Wireless Networks'', First Edition, Pearson
   Education, 2002.


