* <<<702>>> MOBILE COMPUTING
:properties:
:author: Dr. V. S. Felix Enigo and Ms. A. Beulah
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |


** COURSE OBJECTIVES
- Understand the basic concepts of mobile computing
- Be familiar with the protocol stack
- Be exposed to Ad-Hoc networks
- Learn the basics of mobile telecommunication system
- Gain knowledge about different mobile platforms and application development environments.

{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Introduction to Mobile Computing; Media Access Control (MAC): Motivation for a specialized MAC-- SDMA -- FDMA -- TDMA -- CDMA -- 
Comparison of S/T/F/CDMA; Wireless LAN: Infrastructure based and adhoc networks -- IEEE 802.11 -- Bluetooth.
 
{{{unit}}}
|UNIT II | NETWORK LAYER | 9 |
Mobile IP: Goals, assumptions and requirements -- Entities and terminology -- IP packet delivery -- 
Agent discovery -- Registration --Tunneling and encapsulation -- Optimizations; AdHoc: Routing -- 
Proactive routing protocol-DSDV -- Reactive routing protocol -- DSR, AODV.

{{{unit}}}
| UNIT III | TRANSPORT AND APPLICATION LAYER | 9 |
Mobile Transport Layer: Traditional TCP -- Classical TCP improvements; Wireless Application Protocol(WAP): 
Architecture -- WDP -- WTLS -- WTP --WSP -- WAE -- WML --WTA.

{{{unit}}}
|UNIT IV | MOBILE TELECOMMUNICATION SYSTEM | 9 |
Introduction; Global System for Mobile Communication (GSM): Mobile services --
System architecture -- Radio interface -- Localization and
calling -- Handover -- Security; General Packet Radio Service (GPRS); 
Universal Mobile Telecommunication System (UMTS): UMTS system architecture -- UTRAN -- Core network -- 
Handover.

{{{unit}}}
|UNIT V | MOBILE PLATFORMS AND APPLICATION ENVIRONMENTS | 9 |
iOS: iOs Architecture Layers -- iOS Simulator; Android: Platform architecture -- Developing android applications -- Anatomy of android applications --
Android SDK; Windows Phone: Platform architecture -- Silverlight framework; Mobile Web: Being mobile friendly -- WebKit -- Web vs Native vs Hybrid -- 
Mobile web application frameworks.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Identify the functionalities of various MAC protocols (K3)
- Explain the functionalities of mobile network layer and routing in Ad hoc networks (K3)
- Analyze the transport and application layer protocols (K3)
- Explain the basics of mobile telecommunication system (K2)
- Develop a mobile application (K3).

** TEXT BOOKS
1. Jochen H Schller, ``Mobile Communications'',  Pearson Education, New Delhi, 2nd Edition, 2007. (Unit I -IV).
2. Helal, Sumi, Raja Bose, Wendong Li, ``Mobile Platforms and   Development Environments.'' Synthesis Lectures on Mobile and
   Pervasive Computing, 2012. (Unit V)

** REFERENCES
1. Helal, Abdelsalam A, et al. ``Any Time, Anywhere Computing: Mobile Computing Concepts and Technology''. Vol. 522. Springer Science & Business Media, 1st Edition, 1999.
2. Dharma Prakash Agarval, Qing and An Zeng, ``Introduction to Wireless and Mobile systems'',Thomson Asia,  3rd Edition, 2005.
3. Uwe Hansmann, Lothar Merk, Martin S Nicklons and Thomas Stober,  ``Principles of Mobile Computing'', Springer, 2003.
4. William C Y Lee, ``Mobile Cellular Telecommunications--Analog and  Digital Systems'', 2nd Edition,Tata Mc Graw Hill Edition ,2006.
5. C K Toh, ``AdHoc Mobile Wireless Networks'',  Pearson  Education, 1st Edition, 2002.


