* <<<702>>> MOBILE COMPUTING
:properties:
:author: Dr. V. S. Felix Enigo and Ms. A. Beulah
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
The student should be made to:
- Understand the basic concepts of mobile computing
- Be familiar with the network protocol stack
- Learn the basics of mobile telecommunication system
- Be exposed to Ad-Hoc networks
- Gain knowledge about different mobile platforms and application development Environments

{{{unit}}}
|Unit I | Introduction | 9 |
Mobile Computing: Mobile Computing Vs wireless Networking – Mobile Computing Applications – Characteristics of Mobile computing – Structure of Mobile Computing Application; MAC: Motivation for a specialized MAC- SDMA – FDMA – TDMA – CDMA – Comparison of S/T/F/CDMA.

{{{unit}}}
|Unit II | Mobile Internet Protocol and Transport Layer | 9 |
Mobile IP: Goals, assumptions and requirements - Entities and terminology - IP packet delivery - Agent discovery -Registration -Tunneling and encapsulation – Optimizations;  Traditional TCP – Classical TCP improvements: Classical TCP improvements -   Indirect - Snooping - Mobile TCP - Fast retransmit/fast recovery - Transmission/time-out freezing - Selective retransmission -Transaction-oriented TCP.
{{{unit}}}
|Unit III | <Title> | <Hours> |

{{{unit}}}
|Unit IV | <Title> | <Hours> |

{{{unit}}}
|Unit V | <Title> | <Hours> |


\hfill *Total: <Total Hours>*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
      
** References
1. Stephen Marsland, ``Machine Learning – An Algorithmic Perspective'', Second Edition, Chapman and Hall/CRC Machine Learning and Pattern Recognition Series, 2014.
