* <<<703>>> COMPUTER GRAPHICS AND MULTIMEDIA
:properties:
:author: Ms. S. Lakshmi Priya and Mr. N. Sujaudeen
:date: 13-11-18
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To gain knowledge on different display devices and its working principles
- To understand the 2D and 3D dimensional graphics representation and object transformations
- To understand illumination principles and color models used in output devices
- To understand basic concepts of multimedia
- To explore Blender graphics tool and design animations.

#+begin_comment
 UnitI I - Random and Raster scan systems are added.
 Unit III - B SPlines removed
 Unit V changed to accomodate Multimedia concepts.
#+end_comment

{{{unit}}}
|UNIT I | DISPLAY SYSTEMS AND OUTPUT PRIMITIVES | 8 |
Introduction to computer graphics -- Applications; Overview of
graphics systems: Video display devices -- Raster scan systems --
Random scan systems; Output primitives: Points and lines --loading the
frame buffer -- Line drawing algorithms: DDA and Bresenham's line
drawing algorithms -- Circle and ellipse generating algorithms -- Pixel
addressing and object geometry.

{{{unit}}}
|UNIT II | TWO DIMENSIONAL GRAPHICS | 9 |
Two dimensional geometric transformations: Basic Transformations --
Matrix representations and homogeneous coordinates -- Composite
transformations; Two dimensional viewing: Viewing pipeline -- viewing
coordinate reference frame -- Window to viewport coordinate
transformation -- Clipping operations: point and text clipping -- Line
and polygon clipping algorithms.

{{{unit}}}
|UNIT III | THREE DIMENSIONAL GRAPHICS | 10 |
Three dimensional concepts; Three dimensional object representations:
Polygon surfaces -- Polygon tables -- Plane equations -- Polygon
meshes -- Curved Lines and surfaces -- Quadratic surfaces-- Blobby
objects -- Spline representations -- Bezier curves and surfaces; Three
dimensional geometric and modeling transformations: Translation --
Rotation -- Scaling -- composite transformations; Three dimensional
viewing: Viewing pipeline -- Viewing coordinates -- Projections --
View volumes -- Clipping.

{{{unit}}}
|UNIT IV | ILLUMINATION MODELS AND ANIMATION | 8 |
Light sources -- Basic illumination models: Ambient, Diffuse, Specular
Components of the Phong model; Color Models: Properties of light --
Standard primaries and chromaticity diagram -- RGB, YIQ, CMY, HSV and
HLS color models; Computer Animation: Design of animation sequences --
Keyframe systems -- Motion specifications.

{{{unit}}}
|UNIT V | MULTIMEDIA | 10 |
Multimedia Systems Design:Multimedia Elements -- Multimedia
applications --Multimedia Systems Architecture -- Defining objects for
multimedia systems -- Multimedia data interface standards; Compression
and decompression; Data and file format standards; Hypermedia
Messaging; Case Study - Blender Graphics: Fundamentals –- Drawing
Basic Shapes -- Modelling –- Shading & Textures.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
 - Apply the algorithms to manipulate output primitives such as line,
   circle, ellipse (K3)
 - Demonstrate transformations, representations and clipping on 2D
   objects and map window to viewport transformations (K3)
 - Apply three Dimensional concepts like representations, geometric
   transformations, and projections (K3)
 - Understand the working of different illumination and color models
   used to render an animation scene (K2)
 - Understand different types of multimedia file formats, compression
   techniques and design basic 3D Scenes using Blender. (K2)

** TEXT BOOKS
1. Donald Hearn and Pauline Baker M, ``Computer Graphics'', Prentice
   Hall, New Delhi, 2007. 
2. Andleigh, P. K and Kiran Thakrar, ``Multimedia Systems and
   Design'', PHI, 2003. 

** REFERENCES
1. Foley, Vandam, Feiner and Hughes, ``Computer Graphics: Principles
   and Practice'', 2nd Edition, Pearson Education, 2003.
2. Jeffrey McConnell, ``Computer Graphics: Theory into Practice'',
   Jones and Bartlett Publishers, 2006.
3. Hill F S Jr., ``Computer Graphics'', Maxwell Macmillan, 1990.
4. Peter Shirley, Michael Ashikhmin, Michael Gleicher, Stephen R
   Marschner, Erik Reinhard, KelvinSung, and AK Peters, ``Fundamentals
   of Computer Graphics'',CRC Press, 2010.
5. https://www.blender.org/support/tutorials/
