* <<<704>>> MANAGEMENT AND ETHICAL PRACTICES
:properties:
:author: Dr. J. Suresh and Dr. R. Kanchana
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To train basic and applied fields of Management
- To improve the Managerial skills 
- To prepare the students on the functional areas of Management, and analytical skills
- To prepare the students to the management world.
- To  create an awareness on Engineering Ethics and Human Values


{{{unit}}}
|UNIT I | OVERVIEW OF MANAGEMENT & PLANNING | 9 |
Organization -- Role of managers -- Evolution of Management thought --
Managing globally -- Strategies for International Business. Planning
process -- Types of plans -- Decision Making -- Types of decision --
Decision making Process -- Rational Decision Making Process --Decision
Making under different conditions.

{{{unit}}}
|UNIT II | ORGANIZING AND DIRECTING | 9 |
Nature and purpose of organizing -- Line and Staff authority --
Departmentation -- Centralization and Decentralization -- Delegation
of authority -- Staffing -- Selection and Recruitment -- Orientation
-- Performance Appraisal. Motivation and Satisfaction -- Motivation
Theories Leadership -- Leadership theories -- Hurdles to effective
communication.

{{{unit}}}
|UNIT III | CONTROLLING | 9 |
Process of controlling -- Types of control -- Budgetary and
non-budgetary control techniques -- Managing Productivity -- Cost
Control -- Purchase Control -- Maintenance Control -- Quality Control
-- Planning operations.

{{{unit}}}
|UNIT IV | ETHICS IN ENGINEERING | 9 |
Senses of Engineering Ethics -- Variety of moral issues -- Types of
inquiry -- Moral dilemmas -- Moral Autonomy -- Kohlberg's theory --
Gilligan's theory -- Consensus and Controversy -- Models of
professional roles - Theories about right action -- Self-interest --
Customs and Religion -- Uses of Ethical Theories.

{{{unit}}}
|UNIT V | SAFETY, RESPONSIBILITIES AND RIGHTS | 9 |
Safety and Risk -- Assessment of Safety and Risk -- Risk Benefit
Analysis and Reducing Risk - Respect for Authority -- Collective
Bargaining -- Confidentiality -- Conflicts of Interest -- Occupational
Crime -- Professional Rights -- Employee Rights -- Intellectual Property
Rights (IPR) -- Discrimination.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand basic and applied fields of Management (K2)
- Understand and practice Managerial skills (K3)
- Understand the functional areas of Management, and analytical skills (K2)
- Understand and practice Engineering Ethics and Human Values (K3)
      
** REFERENCES
1. Hellriegel, Slocum & Jackson, ``Management -A Competency Based
   Approach'', Thomson South Western, 10th edition, 2007.
2. Harold Koontz, Heinz Weihrich and Mark V Cannice, ``Management-A
   global & Entrepreneurial Perspective'', Tata Mcgraw Hill, 12th
   edition, 2007.
3. Stephen P. Robbins and Mary Coulter, ``Management'', Prentice Hall
   of India,8th edition.
4. Charles W L Hill,Steven L McShane, ``Principles of Management'',
   Mcgraw Hill Education, Special Indian Edition, 2007.
5. Mike W. Martin and Roland Schinzinger, ``Ethics in Engineering'',
   Tata McGraw Hill, New Delhi, 2003.
6. Govindarajan M, Natarajan S, Senthil Kumar V. S, ``Engineering
   Ethics'', Prentice Hall of India, New Delhi, 2004.
