* <<<OE5>>> MACHINE LEARNING APPLICATIONS
:properties:
:author: S. Rajalakshmi
:end:

#+begin_comment
- 1. No equivalent course in AU 2017 Curriculum
- 2. Framed the syllabus with a balance of theory concept and practical implementation
- 3. Text book and syllabus are different from M.E syllabus
- 4. Five Course outcomes specified and aligned with units
- 5. Suggestive experiments are given
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 2 | 0 | 2 | 3 |

** COURSE OBJECTIVES
- To understand the need and types of machine learning techniques for
  various problems
- To study about the various supervised learning
  algorithms in machine learning
- To choose appropriate machine learning algorithms to solve realistic
  problems.

{{{unit}}}
| UNIT I | MACHINE LEARNING LANDSCAPE | 5 |
Machine learning and it's use; Types of machine learning; Challenges
of machine learning; Testing and validating.

{{{unit}}}
| UNIT II | DEVELOPING A MACHINE LEARNING APPLICATION| 6 |
Working with real data -- Frame the problem -- Select performance
measure -- Check assumptions -- Get the data -- Discover and visualize
the data -- Data preparation -- Select and train model -- Fine tune
model -- Launch the system.

{{{unit}}}
|UNIT III | CLASSIFICATION AND REGRESSION | 8 |
Classification: Training a binary classifier -- Performance measures
-- Multiclass classification; Regression: Linear regression --
Gradient descent; Support Vector Machines: Linear SVM classification
-- Nonlinear SVM classification.

{{{unit}}}
|UNIT IV | TREE MODELS AND ENSEMBLE LEARNING | 6 |
Decision Trees: Training and visualizing trees -- Making predictions
-- Estimating class probabilities -- CART training algorithm --
Regularization of hyperparameters; Ensemble learning: Voting
classifiers -- Bagging -- Random forests -- Boosting.

{{{unit}}}
|UNIT V | ARTIFICIAL NEURAL NETWORKS  | 5 |
From Biological to Artificial Neurons: Biological neurons -- Logical
computations with neurons -- Perceptron -- Multi-Layer Perceptron and
backpropagation; Training a MLP network -- Fine tuning neural network
hyperparameters; Introduction to Deep Learning.
Document classification using clustering -- Handwritten character
recognition.

# Case study: E-mail spam detection --
# Sentiment analysis -- 

\hfill *Theory Periods: 30*

** SUGGESTIVE EXPERIMENTS
 - Data analysis
 - Develop a machine learning application using California housing prices dataset 
 - Classification of Iris dataset using multiclass classification
 - Loan amount prediction using linear regression
 - E-mail spam detection using support vector machine
 - Diabetic decision making using decision tree
 - Handwritten character recognition using neural networks
# - Classification of Iris dataset using Naive Bayes model
# - Document grouping using K-means clustering
# - Sentiment analysis / Handwritten character recognition using Ensemble techniques

\hfill *Practical Periods: 30*

\hfill *Total Periods: 60*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the basic concepts and types of machine learning (K2)
- Understand the various steps in developing a machine learning application (K2)
- Apply various algorithms for classification and regression tasks (K3)
- Apply tree and ensemble models for various problems (K3)
- Apply the neural network algorithm for real world problems (K3).
# - Develop solutions using clustering and ensembling methods for machine learning tasks (K3)
      
** TEXT BOOKS
1. Aurelien Geron, ``Hands-On Machine Learning with Scikit-Learn and
   TensorFlow'', O'Reilly Media, 2017.

** REFERENCES
1. Stephen Marsland, ``Machine Learning -- An Algorithmic
   Perspective'', Second Edition, Chapman and Hall/CRC Machine
   Learning and Pattern Recognition Series, 2014.
2. Jason Bell, ``Machine learning -- Hands on for Developers and
   Technical Professionals'', First Edition, Wiley, 2014.
3. Richert, Willi, ``Building Machine Learning Systems with Python'',
   Packt Publishing Ltd, 2013.
4. Tom M. Mitchell, ``Machine Learning'', McGraw-Hill Education
   (India) Private Limited, 2013.
5. Andreas C. Muller, Sarah Guido, ``Introduction to Machine
   Learning with Python'', O'Reilly Media, 2016.



