* <<<OE6>>> WEB TECHNOLOGY
:properties:
:author: Dr. V. S. Felix Enigo 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 2 | 0 | 2 | 3 |

** Course Objectives
- Understand the Web Client/Server environment. 
- Learn to design static web pages using HTML and CSS.
- Learn to design interactive websites using Java Script and DOM.
- Be familiar with creating web applications using Servlets.  
- Be exposed to developing web applications using JSP.

{{{unit}}}
|UNIT I | WEBSITE BASICS, HTML5  | 6   |
Web Essentials: Clients, Servers and Communication – The Internet –
Basic Internet protocols – World Wide web – HTTP Request Message –
HTTP Response Message – Web Clients – Web Servers – Introducing HTML5
– Structuring pages with Semantic elements – Writing more meaningful
Markup – Building better Forms – Audio and Video.

{{{unit}}}
|UNIT II | STYLING WITH CASCADING STYLE SHEETS  | 6   |
CSS3 Basics - HTML for CSS – Styles and Style Sheets - Selectors -
Style Inheritance – Cascading – Formatting Texts – Margins, Padding
and Borders – CSS Transforms, Transitions and Animations - Formatting
Tables and Forms.

{{{unit}}}
|UNIT III | INTERACTIVE CLIENT SIDE SCRIPTING  | 6   |
An introduction to JavaScript – JavaScript DOM Model - Date and
Objects - Regular Expressions- Exception Handling-Validation-Built-in
objects-Event Handling - Host Objects: Browsers and the
DOM-Introduction to the Document Object Model -Intrinsic Event
Handling-Modifying Element Style-The Document Tree-DOM Event Handling.

{{{unit}}}
|UNIT IV | SERVER SIDE SCRIPTING | 6   |
Introduction to Java Servlets- Architecture - Overview - A
Servlet-Generating Dynamic Content-Life Cycle- Parameter
Data-Sessions-Cookies-URL Rewriting.

{{{unit}}}
|UNIT V | ADVANCED SERVER SIDE SCRIPTING | 6   |
Separating Programming and Presentation: JSP Technology
Introduction-JSP and Servlets-Running JSP Applications Basic
JSP-JavaBeans Classes and JSP-Tag Libraries.

\hfill *Theory Periods: 30*

** SUGGESTIVE EXPERIMENTS
- To design a web page using HTML5 semantic elements (Eg. Table,
  article, aside, details, figure, nav etc.)
- Design a web page using form controls and perform in-build
  validation (Eg. Login form, Registration form)
- Use Embedded, inline and External Style sheets for styling a web
  page
- Use Selectors to format texts, margins, padding, borders, tables,
  forms for a web page
- Develop a Java script application using events (Eg. Calculator, Tic
  Tac Toe game)
- Design a web page where the content, formatting change dynamically
  using DOM
- Develop 2-tier web application using HTML form and Servlet
- Develop 3 –tier web application using HTML Form, Servlet and
  Database (Eg. Login Authentication, payroll management system)
- Develop a JSP based 3-tier web application using Scriptlet tags
- Develop a JSP based 2-tier web application using JSTL Tags


\hfill *Practical Periods: 30*

\hfill *Total Periods: 60*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Use Web Client/Server environment for developing applications. (K3)
- Design static Web pages using HTML and CSS.  (K3)
- Design interactive websites using Java Script and DOM. (K3)
- Create web application using Servlets. (K3)
- Develop efficient web application using JSP. (K3)
      
** TEXT BOOKS
1. Jeffrey C. Jackson, ``Web Technologies -- A Computer Science
   Perspective'', Pearson Education, 2006. (Unit I)
2. Mathew Mac Donald, ``HTML5: The Missing Manual'', O'Reilly, 2nd
   Edition, 2013.  (Unit – I, III, IV and V)
3. David McFarland, ``CSS3: The Missing Manual'', 3rd Edition,
   O'Reilly, December 2012. (Unit II)

** REFERENCE BOOKS
1. Jennifer Niederst Robbins, ``Learning Web Design'', O'Reilly, 4th
   Edition.
2. Robert. W. Sebesta, ``Programming the World Wide Web'', Fourth
   Edition, Pearson Education, 2007.
3. Deitel, Deitel, Goldberg, ``Internet & World Wide Web How To
   Program'', Third Edition, Pearson Education, 2006.
4. Marty Hall and Larry Brown, ``Core Web Programming'', Second
   Edition, Volume I and II, Pearson Education, 2001.
5. Bates, ``Developing Web Applications'', Wiley, 2006.

