* <<<PE102>>> ADVANCED DATABASE MANAGEMENT SYSTEMS
:properties:
:author: Ms. A. Beulah and Dr. P. Mirunalini
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
The student should be able to:
- To learn the modeling and design of databases. 
- To acquire knowledge on parallel and distributed databases and their applications. 
- To study the usage and applications of Object Oriented and Intelligent databases. 
- To understand the usage of advanced data models. 
- To learn emerging databases such as XML, Cloud and Big Data. 
- To acquire inquisitive attitude towards research topics in databases. 

{{{unit}}}
|Unit I |Parallel and Distributed Databases| 9 |
Database System Architectures: Centralized and Client-Server Architectures – Server System Architectures – Parallel Systems- Distributed Systems- Parallel Databases: I/O Parallelism – Inter and Intra Query Parallelism – Inter and Intra operation Parallelism – Design of Parallel Systems- Distributed Database Concepts - Distributed Data Storage – Distributed Transactions – Commit Protocols – Concurrency Control – Distributed Query Processing – Case Studies 


{{{unit}}}
|Unit II | Object and Object Relational Databases | 9 |
Concepts for Object Databases: Object Identity – Object structure – Type Constructors – Encapsulation of Operations – Methods – Persistence – Type and Class Hierarchies – Inheritance – Complex Objects – Object Database Standards, Languages and Design: ODMG Model – ODL – OQL – Object Relational and Extended – Relational Systems: Object Relational features in SQL/Oracle – Case Studies. 

{{{unit}}}
|Unit III | Intelligent Databases | 9 |
Active Databases: Syntax and Semantics (Starburst, Oracle, DB2)- Taxonomy- Applications-Design Principles for Active Rules- Temporal Databases: Overview of Temporal Databases- TSQL2- Deductive Databases: Logic of Query Languages – Datalog- Recursive Rules-Syntax and Semantics of Datalog Languages- Implementation of Rules and Recursion- Recursive Queries in SQL- Spatial Databases- Spatial Data Types- Spatial Relationships- Spatial Data Structures-Spatial Access Methods- Spatial DB Implementation. 

{{{unit}}}
|Unit IV | Advanced Data Models | 9 |
Mobile Databases: Location and Handoff Management - Effect of Mobility on Data Management - Location Dependent Data Distribution - Mobile Transaction Models -Concurrency Control - Transaction Commit Protocols- Multimedia Databases- Information Retrieval- Data Warehousing- Data Mining- Text Mining. 

{{{unit}}}
|Unit V | Emerging Technologies | 9 |
XML Databases: XML-Related Technologies-XMLSchema- XML Query Languages- Storing XML in Databases-XML and SQL- Native XML Databases- Web Databases- Geographic Information Systems- Biological Data Management- Cloud Based Databases: Data Storage Systems on the Cloud- Cloud Storage Architectures-Cloud Data Models- Query Languages- Introduction to Big Data-Storage-Analysis.


\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- To develop in-depth understanding of relational databases and skills to optimize database performance in practice. 
- To understand and critique on each type of databases. 
- To design faster algorithms in solving practical database problems. 
- To implement intelligent databases and various data models. 

** Text Books 
1. Ramez Elmasri, Shamkant B. Navathe, ―Fundamentals of Database Systems‖, Sixth Edition , Pearson, 2011. 
2. Thomas Cannolly and Carolyn Begg, ―Database Systems, A Practical Approach to Design, Implementation and Management‖, Fourth Edition, Pearson Education, 2008. 

** References
1. Henry F Korth, Abraham Silberschatz, S. Sudharshan, ―Database System Concepts‖, Sixth Edition, McGraw Hill, 2011. 
2. C.J.Date, A.Kannan, S.Swamynathan, ―An Introduction to Database Systems‖, Eighth Edition, Pearson Education, 2006. 
3. Carlo Zaniolo, Stefano Ceri, Christos Faloutsos, Richard T.Snodgrass, V.S.Subrahmanian, Roberto Zicari, ―Advanced Database Systems‖, Morgan Kaufmann publishers,2006 

