* <<<PE103>>> SOFTWARE TESTING
:properties:
:author: Dr. K. Madheswari and Dr. A. Chamundeswari
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the importance of testing in project development
- To understand Software Quality Assessment standards
- To analyze the product quality
- To use various testing methods in projects
- To apply automation tools for software testing in projects

{{{unit}}}
|UNIT I|INTRODUCTION|9| 
Introduction to Software Quality -- Challenges – Objectives –- Quality
Factors -– Components of SQA –- Contract Review –- Development and
Quality Plans –- SQA Components in Project Life Cycle –- SQA Defect
Removal Policies –- Reviews.

{{{unit}}}
|UNIT II |TESTING METHODOLOGIES|9| 
Basics of Software Testing –- Test Generation from Requirements –-
Finite State Models –- Combinatorial Designs -- Test Selection;
Minimization and Prioritization for Regression Testing –- Test
Adequacy; Assessment and Enhancement.

{{{unit}}}
|UNIT III|TEST STRATEGIES |9| 
Testing Strategies –- White Box and Black Box Approach –- Integration
Testing –- System and Acceptance Testing –- Performance Testing –-
Regression Testing -- Internationalization Testing –- Ad-hoc Testing
–- Website Testing –- Usability Testing –- Accessibility Testing.

{{{unit}}}
|UNIT IV| TEST AUTOMATION AND MANAGEMENT |9|
Test plan –- Management –- Execution and Reporting –- Software Test
Automation –- Automated Testing tools -- Hierarchical Models of
Software Quality –- Configuration Management –- Documentation Control.

{{{unit}}}
|UNIT V|SQA IN PROJECT MANAGEMENT |9|
Project progress control –- costs –- quality management standards –-
project process standards –- management and its role in SQA –- SQA
unit.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to: 
- Understand the importance of testing in project development (K2). 
- Understand the Software Quality Assessment standards (K2).
- Analyze the product Quality (K3).
- Use various testing methods in projects(K3).
- Apply Automation tools for software testing in projects (K3).


** TEXT BOOKS
1. AdityaMathur, ``Foundations of Software Testing'', Pearson
   Education, 2008
2. Alan C Gillies, ``Software Quality Theory and Management'', Cengage
   Learning, Second Edition, 2003.
	
** REFERENCES
1. Daniel Galin, ``Software Quality Assurance -- From Theory to
   Implementation'', Pearson Education, 2009.
2. Robert Furtell, Donald Shafer, and Linda Shafer, ``Quality Software
   Project Management'', Pearson Education Asia, 2002.
3. Ron Patton, ``Software Testing'', Second Edition, Pearson
   Education, 2007.
4. SrinivasanDesikan, Gopalaswamy Ramesh, ``Software Testing --
   Principles and Practices'', Pearson Education, 2006.
5. Yogesh Singh, ``Software Testing'', Cambridge University
   Press, 2012.

