* <<<PE101>>> C# AND .NET PROGRAMMING
:properties:
:author: S.Rajalakshmi & V.S. Felix Enigo
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To learn the basic programming and the object oriented programming concepts in C#.
- To write window based applications and web applications using ADO.NET and ASP.NET.
- To understand the basics of assemblies, communication and workflow framework. 
  

{{{unit}}}
|Unit I | C# LANGUAGE BASICS (Ch 1 to 7)| 9 |
Introduction to .Net Architecture; Core C#:  Variables -- Data Types -- Flow control-- Enumerations -- namespaces -- main method -- comments ;  Objects and Types ; Inheritance; Generics; Arrays and Tuples; Operators and Casts; Examples in C#.

{{{unit}}}
|Unit II | C# ADVANCED FEATURES (Ch 8, 9,10,15,16,24)| 11 |
Delegates, Lambdas and Events; Strings and Regular Expressions; Collections;  Reflection; Errors and Exceptions; Manipulating Files: Managing file system -- File operations.

{{{unit}}}
|Unit III | WINDOWS BASED APPLICATIONS AND DATA (Ch 35, 32) | 8 |
Core Windows Presentation Foundation (WPF): Geometry and transformations -- Brushes -- Controls -- Layouts -- Styles and Resources -- Triggers -- Templates; Core ADO .Net: Overview -- Database Connections -- Commands -- Data Reader -- Dataset Class -- Data Adapter; Case study: Library management system. 

{{{unit}}}
|Unit IV | ASP .NET (Ch 39, 40) | 9 |
Core ASP .Net: .Net Framework for Web Applications -- Web Technologies -- Handlers and Modules -- Global Application Class -- Request and Response -- State Management; ASP .Net Web Forms:  ASPX Page Model -- Master Pages -- Navigation -- Validating User input -- Accessing Data -- Case study: E-commerce website development.

{{{unit}}}
|Unit V | ASSEMBLIES, WCF AND WWF (Ch 19, 43, 45)  | 8 |
Assemblies: Application Domains -- Shared Assemblies -- Versioning; Windows Communication Foundation (WCF) : Overview -- Creating a simple service and client -- Contracts; Windows Workflow Foundation (WWF): Overview -- Activities -- Workflows.


\hfill *Total: 45 Hours*

** Course Outcomes
After the completion of this course, students will be able to: 
- Apply object oriented concepts in program development using C#. (K3)
- Develop windows based applications using C# in .NET framework using WPF. (K3)
- Develop web applications using ASP.Net (K3)
- Develop database applications using ADO.Net. (K3)
- Understand the basic concepts of Assemblies, WCF and WWF. (K2)
 
      
** Text Book
1.	Christian Nagel, Bill Evjen, Jay Glynn, Karli Watson, Morgan Skinner, ``Professional C# 2012 and .NET 4.5'', Wiley, 2012.

** References
1.	Ian Gariffiths, Mathew Adams, Jesse Liberty, ``Programming C# 4.0'', O'Reilly, Fourth Edition, 2010.
2.	Andrew Troelsen, ``Pro C# 5.0 and the .NET 4.5 Framework'', Apress publication, 2012.
3.	Andy Wigley, Daniel Moth, Peter Foot, ``Mobile Development Handbook'', Microsoft Press, 2011.
4.	Harsh Bhasin, ``Programming in C#'', Oxford University Press, 2014.
5.	Herbert Schildt, ``C# 4.0 The Complete Reference'', 1st Edition, Mc Graw Hill Education, 2010.

