* <<<PE208>>> NUMERICAL METHODS WITH PROGRAMMING
:properties:
:author: Dr. J. Suresh  and Dr. S. Saraswathi
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand basic programming constructs.
- To know about Interpolation methods.
- To learn about Numerical Integration.
- To learn about Numerical solutions of equations
- To study Numerical solutions for differential equations

{{{unit}}}
|UNIT I | APPROXIMATE NUMBERS | 9|
Sources of Errors in Numerical Calculations -- Absolute and Relative
Errors -- Representation of Numbers -- Significant Digits -- Errors of
Elementary Operations; Basic Programming Techniques( C/C++)

{{{unit}}}
| UNIT II | INTERPOLATION | 9 |
Finite differences -- Newton’s Forward Interpolation formula -- Newton's Backward interpolation formula -- Central Difference
interpolation formula -- Lagrange’s formula -- Newton’s divided difference interpolation formula -- Inverse Lagrange’s interpolation
formula -- Interpolating with a cubic spline -- Curve Fitting: Method of Least Squares -- Linear and polynomial regression.

{{{unit}}}
| UNIT III | NUMERICAL INTEGRATION | 9 |
Trapezoidal Rule -- Simpson's 1/3 Rule -- Simpson's 3/8 Rule -- Gaussian Quadrature Formula -- Double integration using Trapezoidal
Rule -- Simpson’s Rule

{{{unit}}}
| UNIT IV | NUMERICAL SOLUTION FOR ALGEBRAIC EQUATIONS | 9 |
Direct methods -- Gauss and Gauss–Jordan methods; Iterative methods -- Gauss-Jacobi and Gausss-Seidel methods -- Relaxation method --
Newton’s method for nonlinear simultaneous equations -- Power method for determination eigen values -- convergence of Power method.

{{{unit}}}
|UNIT V | NUMERICAL SOLUTION FOR DIFFERENTIAL EQUATIONS | 9 |
Numerical solution of ordinary differential equations; Single step methods -- Taylor series method -- Picard’s Method -- Euler and
Modified Euler methods -- Runge–Kutta methods of 2nd and 4th order; Multi-step methods -- Miline’s PredictorCorrector formulas -- Adam-Bashforth and Adam-Moulton formulas.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Develop simple applications in C using basic constructs (K3).
- Understanding the Numerical interpolation and integration (K2).
- Provide numerical solutions for differential equations (K3).
- Apply Numerical methods to solve problems drawn from industry and Engineering (K3).
- Assess the reliabilty of Numerical results (K3).
      
** TEXT BOOKS
1. Titus Adrien Beu, "INTRODUCTION TO NUMERICAL PROGRAMMING A Practical Guide for Scientists and Engineers Using Python and C/C++",  CRC Press, 2019.
2. Steven C Chapra, Raymond P Canale, "Numerical Methods for Engineering", Sixth Edition, McGraw-Hill Publications, 2010.

** REFERENCES
1. Jaan Kiusalaas, "Numerical Methods in Engineering with Python 3",  Cambridge University Press,  2013. 
2. Veerarjan, T and Ramachandran, T. "Numerical methods with programming in ‘C’", Second Editiion, Tata McGraw-Hill Publishing.Co.Ltd, 2007.
3. R. W. Hamming, "Numerical Methods for Scientists and Engineerings",  Second Edition, Dover Publications Inc, New York, 1973.
4. Gerald, C. F. and Wheatley, P.O., "Applied Numerical Analysis",  Sixth Edition, Pearson Education Asia, New Delhi, 2006.
5. Brian, ``A friendly introduction to Numerical analysis'', Pearson Education, Asia, New Delhi, 2007.

