* <<<PE207>>> FOUNDATIONS OF DATA SCIENCE
:properties:
:author: Ms. S. Rajalakshmi  and Dr. J. Bhuvana
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn fundamentals of data Science and to use Python for carrying out basic statistical modeling and analysis.
- To identify probability distributions and statistical Inferences used for statistical modeling.
- To obtain necessary knowledge in supervised and unsupervised methods of machine learning.
- To explore the algorithms used for analysing  massive data problems and social networks.
- To learn about topic and graphical models. 


{{{unit}}}
|UNIT I | DATA SCIENCE AND PYTHON | 9 |
Introduction: Computational tools -- Need for data science --
Causality and experiments; Python: Array computing -- Vectors --
Basics of numerical Python arrays -- Vectorization -- Advanced
vectorization of functions -- Matrices and arrays -- Reading and
writing spreadsheet files; Visualization: Graphs and tables.

{{{unit}}}
|UNIT II | PROBABILITY AND STATISTICS | 9 |
Randomness -- Empirical distributions -- Bayes theorem; Testing
hypothesis -- Estimation -- Why the mean matters -- Prediction --
Inference for regression.

{{{unit}}}
|UNIT III | MACHINE LEARNING ALGORITHMS | 9 |
Perceptron algorithm -- Kernel functions -- Overfitting and uniform
convergence -- Regularization -- Support Vector Machines -- Strong and
weak learning -- Boosting -- Stochastic Gradient Descent.

{{{unit}}}
|UNIT IV | DATA STREAMS AND CLUSTERING | 9 |
Frequency moments of data streams -- Matrix algorithms using sampling
; k-Means clustering -- Spectral clustering -- Community finding --
Graph partitioning.

{{{unit}}}
|UNIT V | TOPIC MODELS AND GRAPHICAL MODELS | 9 |
Topic Models -- Idealized Model -- Nonnegative Matrix Factorization
--Latent Dirichlet Allocation -- Hidden Markov Models -- Graphical
Models and Belief Propagation -- Bayesian Belief Networks -- Markov
Random Fields.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Develop Python programs to perform analysis on data. (K3)
- Understand various probability distributions and statistical inferences. (K2)
- Develop applications to demonstrate machine learning algorithms in practice. (K3)
- Understand the principles of handling data streams. (K2)
- Discuss topic and graphical modeling techniques in real world problem.(K2)
 
** TEXT BOOKS
1. Avrim Blum, John Hopcroft and Ravindran Kannan, ``Foundations of
   Data Science'', Vorabversion eines Lehrbuchs, 2016.
2. Ani Adhikari and John DeNero, ``Computational and Inferential
   Thinking: The Foundations of Data Science'', GitBook, 2017.

** REFERENCE BOOKS
1. Hans Petter Langtangen, ``A Primer on Scientific Programming with
   Python'', 4th Edition, Springer, 2016.
2. Jonathan Dinu, ``Foundations of Data Science: A Practical
   Introduction to Data Science with Python'', Addison-wesley Data &
   Analytics Series, 2016.
3. Jure Leskovek, Anand Rajaraman and Jeffrey Ullman, ``Mining of
   Massive Datasets'', V2.1, Cambridge University Press, 2014.
4. EMC Education Services, ``Data Science and Big Data Analytics:
   Discovering, Analyzing, Visualizing and Presenting Data'', Wiley
   publishers, 2015.
5. Cathy O'Neil and Rachel Schutt. ``Doing Data Science, Straight Talk
   From The Frontline'', O'Reilly, 2014.


