* <<<PE201>>> CLOUD COMPUTING
:properties:
:author: Ms. Y. V. Lokeswari and Dr. J. Suresh
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the concepts of virtualization and virtual machines.
- To learn about virtualization infrastructure.
- To understand the principles of Cloud Architecture, Models and
  Infrastructure.
- To explore and experiment various Cloud deployment environments.
- To learn about the security issues in the cloud environment. 

{{{unit}}}
|UNIT I|CLOUD ARCHITECTURE MODELS AND INFRASTRUCTURE|8| 
Cloud Architecture: System Models for Distributed and Cloud Computing
-- NIST Cloud Computing Reference Architecture -- Cloud deployment
models -- Cloud service models; Cloud Infrastructure: Architectural
Design of Compute and Storage Clouds -- Layered Cloud Architecture
Development -- Design Challenges -- Inter Cloud Resource Management --
Resource Provisioning and Platform Deployment.


{{{unit}}}
|UNIT II |INTRODUCTION TO VIRTUALIZATION|9| 
Basics of Virtualization -- Emulation -- Interpretation -- Binary
Translation -- Virtualization Advantages -- Virtual Machine Basics --
Taxonomy of Virtual Machines -- Process Virtual Machines -- System
Virtual Machines -- Hypervisor -- Key Concepts -- Virtualization
structure -- Implementation levels of virtualization -- Virtualization
Types: Full Virtualization -- Para Virtualization -- Hardware
Virtulization.

{{{unit}}}
|UNIT III|VIRTUALIZATION INFRASTRUCTURE|9| 
Comprehensive Analysis -- Resource Pool -- Testing Environment --
Virtual Workloads -- Provision Virtual Machines -- Desktop
Virtualization -- Network Virtualization -- Server and Machine
Virtualization -- Storage Virtualization -- System-level of Operating
Virtualization -- Application Virtualization-- Virtualization of CPU,
Memory and I/O devices -- Virtual clusters and Resource Management --
Virtual Machine Monitors: KVM, Xen, VMWareESXi server.

{{{unit}}}
|UNIT IV| CLOUD DEPLOYMENT ENVIRONMENT|12|
Parallel Programming Framework: Hadoop Map Reduce -- Google App Engine
-- Amazon AWS -- Microsoft Azure; Cloud Software Environments --
Eucalyptus -- OpenStack -- OpenNebula -- Aneka -- CloudSim.


{{{unit}}}
| UNIT V | CLOUD SECURITY | 7 |
Data Security and Storage; Identity and Access Management(IAM) -- IAM
Challenges -- IAM Architecture and Practice; Security Management in
the Cloud -- Security Management Standards -- SaaS, Paas and IaaS
Availability Management -- Access Control; Security-As-A-[Cloud]
Service

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to:
- Understand the design challenges in cloud environment (K2)
- Apply the concept of virtualization and analyse its types (K3)
- Experiment with virtualization of hardware resources and Virtual
  Machine Monitors (K3)
- Develop and deploy services on cloud and be able to set up a private
  cloud environment using open source software (K3)
- Understand security challenges in cloud environment (K2)


** TEXT BOOKS
1. Kai Hwang, Geoffery C. Fox and Jack J. Dongarra, ``Distributed and
   Cloud Computing: Clusters, Grids, Clouds and the Future of
   Internet'', First Edition, Morgan Kaufman Publisher, an Imprint of
   Elsevier, 2012. (Unit I, II, IV)
2. Srinivasan A, Suresh J, ``Cloud Computing: A practical Approach for
   Learning and Implementation'', Pearson Education
   India, 2014. (Units I, II, III, IV)

** REFERENCES
1. Tim Mather, Subra Kumaraswamy, and Shahed Latif , ``Cloud Security
   and Privacy: an enterprise perspective on risks and compliance'',
   O'Reilly Media, Inc., 2009. (Unit V)
2. Danielle Ruest, Nelson Ruest, ``Virtualization: A Beginner's
   Guide'', McGraw-Hill Osborne Media, 2009.
3. James E. Smith, Ravi Nair, ``Virtual Machines: Versatile Platforms
   for Systems and Processes'', Elsevier/Morgan Kaufmann, 2005.
4. William von Hagen, ``Professional Xen Virtualization'', Wrox
   Publications, January, 2008.
5. David Marshall, Wade A. Reynolds, ``Advanced Server Virtualization:
   VMware and Microsoft Platform in the Virtual Data Center'',
   Auerbach Publications, 2006.
