* <<<PE202>>> CYBER FORENSICS
:properties:
:author: Dr. A. Chamundeswari and Dr. S. Saraswathi
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |
#+begin_comment
Unit-1:   AU-Unit I included. 

Unit-2:  AU-Unit I topics included
         AU-Unit I data acquisition topics is elaborated 

Unit-3: AU-Unit II topics included
        AU-Unit III topics included

Unit-4: AU-Unit III topics included 

Unit-5:  New tools topics included
         Ehtical hacking given in AU-Unit IV in SNU syllabus and V is not included in SNU.
#+end_comment

** COURSE OBJECTIVES
- To learn computer forensics and understand incident response.
- To know the methods to collect and store digital evidence.  
- To understand the approaches to analyse and validate data.
- To investigate network and mobile forensic data.
- To be familiar with forensics tools.  


{{{unit}}} 
| UNIT I | 	INTRODUCTION TO COMPUTER FORENSICS | 9 |
Understanding computer forensics; Introduction to the Incident
Response Process; Preparing for Incident Response: Overview of
Pre-incident Preparation -- Identifying Risk -- Preparing Individual
Hosts -- Preparing a Network -- Establishing Appropriate Policies and
Procedures -- Creating a Response Toolkit -- Establishing an Incident
Response Team.

{{{unit}}}
|UNIT II | DATA ACQUISITION | 9 |
After Detection of an Incident: Initial respo in SNU syllabusnse phase
-- Incident motification procedure -- Recording after initial
detection -- Incident declaration -- Assembling the CSIRT --
Traditional investigative steps -- Conducting interviews --Response
strategy; Data Acquisition: Storage formats -- Determining the best
acquisition method -- Image acquisitions -- Acquisition tools --
Validating data acquisitions -- RAID data acquisitions -- Remote
network acquisition tools.

{{{unit}}}
|UNIT III | ANALYSIS AND VALIDATION | 9 |
Processing Crime and Incident Scenes: Identifying digital evidence --
Private sector IS -- Processing law enforcement CS -- Search --
Securing CS -- Seizing -- Storing -- Digital hash -- Reviewing a case;
Working with Windows and DOS Systems: Examining NTFS disks; Computer
Forensics Analysis and Validation: Data to collect and analyze --
Validating -– Data hiding techniques -– Remote acquisition.

{{{unit}}}
|UNIT IV | NETWORK AND MOBILE FORENSIC | 9 |
Network Forensics: Developing standard procedures for network
forensics -- Using network tools; E-mail Investigations: Understanding
E-mail servers -- Using specialized E-mail forensics tools; Cell Phone
and Mobile Device Forensics: Understanding mobile device forensics --
Understanding acquisition procedures for cell phones and mobile
devices.

# Mobile Network Forensic: Introduction -- Mobile Network Technology --
# Investigations -- Collecting Evidence -- Wher in SNU syllabuse to seek Digital Data
# for further Investigations -- Interpretation of Digital Evidence on
# Mobile Network.

{{{unit}}}
|UNIT V | COMPUTER FORENSIC TOOLS| 9 |
The Investigator's Office and Laboratory: Understanding forensics lab
certification requirements -- Determining the physical requirements
for a computer forensics lab; Computer Forensic tools: Encase -- Helix
-- FTK -- Autopsy -- Sleuth kit forensic browser -- FIRE -- Found
stone forensic toolKit -- WinHex -- Linux and other open source tools.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the preparation of incident response (K2)
- Apply data acquisition techniques (K3)
- Analyze and validate forensics data (K3)
- Understand network and mobile forensics (K2)
- Use forensics tools (K3).

** TEXT BOOKS 
1. Chris Prosise, Kevin Mandia, ``Incident Response and Computer Forensics'', Second Edition, McGraw-Hill 2003.
2. Nelson, Phillips, Enfinger, Steuart, ``Computer Forensics and Investigations'', Cengage Learning, India Edition, 2008.

** REFERENCES 
1. Dhillon G, ``Principles of Information Systems Security'', John Wiley & Sons, 2007.
2. Whitman M E, Mattord H J, ``Principles of Information Security'', Third Edition, Thompson Course Technology, 2009.
3. John R Vacca, ``Computer Forensics'', Cengage Learning, 2005.
4. Marjie T Britz, ``Computer Forensics and Cyber Crime: An Introduction'', Third Edition, Prentice Hall, 2013.
5. Marcella Jr, Albert, and Doug Menendez, ``Cyber Forensics: a Field Manual for Collecting, Examining, and Preserving Evidence of Computer Crimes'', Auerbach Publications, 2007.
