* <<<PE202>>> CYBER FORENSICS
:properties:
:author: Dr. A. Chamundeswari and Dr. S. Saraswathi
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To learn computer forensics and understand incident responce.
-	To konw the methods to collect and store digital evidence.  
-	To Understand the approaches to analyse and validate data.
-	To investigate network and mobile forensic data.
-	To be familiar with forensics tools.  


{{{unit}}}
|Unit I | 	INTRODUCTION TO COMPUTER FORENSICS | 9 |
Understanding computer forensics; Introduction to the Incident Response Process; Preparing for Incident Response: Overview of Pre-incident Preparation -- Identifying Risk -- Preparing Individual Hosts -- Preparing a Network -- Establishing Appropriate Policies and Procedures -- Creating a Response Toolkit -- Establishing an Incident Response Team.  
{{{unit}}}
|Unit II | DATA ACQUISITION | 9 |
After Detection of an Incident: Overview of the Initial Response Phase -- Establishing an Incident Notification Procedure -- Recording the Details after Initial Detection -- Incident Declaration -- Assembling the CSIRT -- Performing Traditional Investigative Steps -- Conducting Interviews -- Formulating a Response Strategy; Data Acquisition: Understanding Storage Formats for Digital Evidence -- Determining the Best Acquisition Method -- Contingency Planning for Image Acquisitions -- Using Acquisition Tools -- Validating Data Acquisitions -- Performing RAID Data Acquisitions -- Using Remote Network Acquisition Tools.
{{{unit}}}
|Unit III | ANALYSIS AND VALIDATION | 9 |
Processing Crime and Incident Scenes: Identifying Digital Evidence -- Collecting Evidence in Private Sector Incident Scenes -- Processing Law Enforcement Crime Scenes -- Preparing for a Search -- Securing a Computer Incident or Crime Scene -- Seizing Digital Evidence at the Scene -- Storing Digital Evidence -- Obtaining a Digital Hash -- Reviewing a Case; Working with Windows and DOS Systems: Examining NTFS Disks; Computer Forensics Analysis and Validation: Determining What Data to Collect and Analyze -- Validating Forensic Data -– Addressing Data Hiding Techniques -– Performing Remote Acquisition.
{{{unit}}}
|Unit IV | NETWORK AND MOBILE FORENSIC | 9 |
Network Forensics: Developing Standard Procedures for Network Forensics -- Using Network Tools;  E-mail Investigations: Understanding E-mail Servers -- Using Specialized E-mail Forensics Tools; Mobile Network Forensic: Introduction -- Mobile Network Technology -- Investigations -- Collecting Evidence -- Where to seek Digital Data for further Investigations -- Interpretation of Digital Evidence on Mobile Network.
{{{unit}}}
|Unit V | COMPUTER FORENSIC TOOLS| 9 |
The Investigator’s Office and Laboratory: Understanding Forensics Lab Certification Requirements -- Determining the physical requirements for a computer forensics lab; Computer Forensic tools: Encase -- Helix -- FTK -- Autopsy -- Sleuth kit Forensic Browser -- FIRE -- Found stone Forensic ToolKit -- WinHex -- Linux dd and other open source tools. 

\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Know how to prepare the incident response (K2)
-	Perform data acquisition techniques(K3)
-	Analyze and validate forensics data (K3)
-	Collect network and mobile forensics investigation data(K2)
-	Use forensics tools (K3)

 ** Text Books: 
1.	Chris Prosise, Kevin Mandia, ``Incident Response and Computer Forensics'', Second Edition, McGraw-Hill 2003. 
2.	Nelson, Phillips, Enfinger, Steuart, ``Computer Forensics and Investigations'', Cengage Learning, India Edition, 2008. 

** References 
1.	Dhillon G, ``Principles of information systems security'', John Wiley & Sons, 2007.
2.	Whitman ME, Mattord HJ, ``Principles of information security'', Third Edition, Thompson Course Technology, 2009.
3.	John R.Vacca, ``Computer Forensics'', Cengage Learning, 2005. 
4.	Marjie T.Britz, ``Computer Forensics and Cyber Crime: An Introduction'', Third Edition, Prentice Hall, 2013. 
5.	Marcella Jr, Albert, and Doug Menendez, ``Cyber forensics: a field manual for collecting, examining, and preserving evidence of computer crimes'', Auerbach Publications, 2007.
     

