* <<<PE202>>> CYBER FORENSICS
:properties:
:author: Dr. A. Chamundeswari and Dr. S. Saraswathi
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn computer forensics and understand incident response.
- To know the methods to collect and store digital evidence.  
- To understand the approaches to analyse and validate data.
- To investigate network and mobile forensic data.
- To be familiar with forensics tools.  


{{{unit}}}
| UNIT I | 	INTRODUCTION TO COMPUTER FORENSICS | 9 |
Understanding computer forensics; Introduction to the Incident
Response Process; Preparing for Incident Response: Overview of
Pre-incident Preparation -- Identifying Risk -- Preparing Individual
Hosts -- Preparing a Network -- Establishing Appropriate Policies and
Procedures -- Creating a Response Toolkit -- Establishing an Incident
Response Team.

{{{unit}}}
|UNIT II | DATA ACQUISITION | 9 |
After Detection of an Incident: Initial Response Phase
-- Incident Notification Procedure -- Recording after Initial Detection -- Incident Declaration -- Assembling
the CSIRT -- Traditional Investigative Steps -- Conducting
Interviews --Response Strategy; Data Acquisition:
Storage Formats -- Determining the
Best Acquisition Method -- Image Acquisitions
-- Acquisition Tools -- Validating Data Acquisitions -- RAID Data Acquisitions -- Remote Network Acquisition Tools.

{{{unit}}}
|UNIT III | ANALYSIS AND VALIDATION | 9 |
Processing Crime and Incident Scenes: Identifying Digital Evidence --
Private Sector IS -- Processing Law Enforcement CS -- Search -- Securing CS --
Seizing -- Storing -- Digital Hash --
Reviewing a Case; Working with Windows and DOS Systems: Examining NTFS
Disks; Computer Forensics Analysis and Validation: Data to Collect and Analyze -- 
Validating -– Data Hiding Techniques -– Remote Acquisition.

{{{unit}}}
|UNIT IV | NETWORK AND MOBILE FORENSIC | 9 |
Network Forensics: Developing Standard Procedures for Network
Forensics -- Using Network Tools; E-mail Investigations: Understanding
E-mail Servers -- Using Specialized E-mail Forensics Tools; Cell Phone
and Mobile Device Forensics: Understanding mobile device forensics --
Understanding acquisition procedures for Cell Phones and Mobile
Devices.

# Mobile Network Forensic: Introduction -- Mobile Network Technology --
# Investigations -- Collecting Evidence -- Where to seek Digital Data
# for further Investigations -- Interpretation of Digital Evidence on
# Mobile Network.

{{{unit}}}
|UNIT V | COMPUTER FORENSIC TOOLS| 9 |
The Investigator's Office and Laboratory: Understanding Forensics Lab
Certification Requirements -- Determining the physical requirements
for a computer forensics lab; Computer Forensic tools: Encase -- Helix
-- FTK -- Autopsy -- Sleuth kit Forensic Browser -- FIRE -- Found
stone Forensic ToolKit -- WinHex -- Linux and other open source tools.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the preparation of incident response (K2)
- Apply data acquisition techniques (K3)
- Analyze and validate forensics data (K3)
- Understand network and mobile forensics (K2)
- Use forensics tools (K3)

** TEXT BOOKS 
1. Chris Prosise, Kevin Mandia, ``Incident Response and Computer
   Forensics'', Second Edition, McGraw-Hill 2003.
2. Nelson, Phillips, Enfinger, Steuart, ``Computer Forensics and
   Investigations'', Cengage Learning, India Edition, 2008.

** REFERENCES 
1. Dhillon G, ``Principles of Information Systems Security'', John
   Wiley & Sons, 2007.
2. Whitman ME, Mattord HJ, ``Principles of Information Security'',
   Third Edition, Thompson Course Technology, 2009.
3. John R.Vacca, ``Computer Forensics'', Cengage Learning, 2005.
4. Marjie T.Britz, ``Computer Forensics and Cyber Crime: An
   Introduction'', Third Edition, Prentice Hall, 2013.
5. Marcella Jr, Albert, and Doug Menendez, ``Cyber Forensics: a Field
   Manual for Collecting, Examining, and Preserving Evidence of
   Computer Crimes'', Auerbach Publications, 2007.
