* <<<PE406>>> EMBEDDED SYSTEMS
:properties:
:author: Mr. K. R. Sarath Chandran and Ms. S. Angel Deborah
:date: 
:end:

#+startup: showall


| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To learn the architecture and programming of ARM processor.
- To become familiar with the embedded computing platform design and analysis.
- To get thorough knowledge in interfacing concepts.
- To design an embedded system and to develop programs

|Unit I | INTRODUCTION TO EMBEDDED COMPUTING AND ARM PROCESSORS  | 9 |
Complex systems and micro processors– Embedded system design process –Design example: Model train controller- Instruction sets preliminaries - ARM Processor – CPU: programming input and output- supervisor mode, exceptions and traps – Co-processors- Memory system
mechanisms – CPU performance- CPU power consumption. 

|Unit II | EMBEDDED COMPUTING PLATFORM DESIGN  | 9 |
The CPU Bus-Memory devices and systems–Designing with computing platforms – consumer electronics architecture – platform-level performance analysis - Components for embedded programs- Models of programs- Assembly, linking and loading – compilation techniques- Program level performance analysis – Software performance optimization – Program level energy and power analysis and optimization – Analysis and optimization of program size- Program validation and testing.

|Unit III | SENSOR INTERFACING WITH ARDUINO | 9 |
Basics of hardware design and functions of basic passive components-sensors and actuatorsArduino code - library file for sensor interfacing-construction of basic applications

|Unit IV | EMBEDDED FIRMWARE  | 9 |
Reset Circuit, Brown-out Protection Circuit-Oscillator Unit - Real Time Clock-Watchdog Timer -
Embedded Firmware Design Approaches and Development Languages.

|Unit V | EMBEDDED C PROGRAMMING  | 9 |
Introduction-Creating ‗hardware delays‘ using Timer 0 and Timer 1-Reading switches-Adding Structure to the code-Generating a minimum and maximum delay-Example: Creating a portable hardware delay- Timeout mechanisms-Creating loop timeouts-Testing loop timeouts- hardware
timeouts-Testing a hardware timeout


*Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand the basic concepts of machine learning (K2).
      
** References
1. Stephen Marsland, ``Machine Learning – An Algorithmic Perspective'', Second Edition, Chapman and Hall/CRC Machine Learning and Pattern Recognition Series, 2014.
