* <<<PE402>>> HUMAN COMPUTER INTERACTION
:properties:
:author: Ms. K. Madheswari and Dr. A. Chamundeswari
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
-	Learn the foundations of Human Computer Interaction
-	Be familiar with the design technologies for individuals and persons with disabilities
-	Be aware of mobile HCI
-	Learn the guidelines for user interface.


{{{unit}}}
|Unit I | FOUNDATIONS OF HCI | 9 |
The Human: I/O channels – Memory – Reasoning and problem solving; The computer: Devices – Memory – processing and networks; Interaction: Models – frameworks – Ergonomics – styles – elements – interactivity- Paradigms.
{{{unit}}}
|Unit II | DESIGN & SOFTWARE PROCESS | 9 |
Interactive Design basics – process – scenarios – navigation – screen design – Iteration and prototyping. HCI in software process – software life cycle – usability engineering – Prototyping in practice – design rationale. Design rules – principles, standards, guidelines, rules. Evaluation Techniques – Universal Design.
{{{unit}}}
|Unit III | MODELS AND THEORIES | 9 |
Cognitive models –Socio-Organizational issues and stake holder requirements –Communication and collaboration models-Hypertext, Multimedia and WWW.
{{{unit}}}
|Unit IV | MOBILE HCI  | 9 |
Mobile Ecosystem: Platforms, Application frameworks- Types of Mobile Applications: Widgets, Applications, Games- Mobile Information Architecture, Mobile 2.0, Mobile Design: Elements of Mobile Design, Tools.
{{{unit}}}
|Unit V | WEB INTERFACE DESIGN |9 |
UNIT V :             					9                
Designing Web Interfaces – Drag & Drop, Direct Selection, Contextual Tools, Overlays, Inlays and Virtual Pages, Process Flow. Case Studies.


\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Design effective dialog for HCI.
-	Design effective HCI for individuals and persons with disabilities.
-	Assess the importance of user feedback.
-	Explain the HCI implications for designing multimedia/ ecommerce/ e-learning Web sites.
-	Develop meaningful user interface.

** Text Books
1.	Alan Dix, Janet Finlay, Gregory Abowd, Russell Beale, “Human Computer Interaction”, 3rd Edition, Pearson Education, 2004 (UNIT I , II & III)
2.	Brian Fling, “Mobile Design and Development”, First Edition , O‟Reilly Media Inc., 2009 (UNIT –IV)
3.	Bill Scott and Theresa Neil, “Designing Web Interfaces”, First Edition, O‟Reilly, 2009.(UNIT-V)

** References
 1.	Preece J., Rogers Y., Sharp H., Baniyon D., Holland S. and Carey T. Human Computer Interaction, Addison-Wesley, 1994.
2.	B. Shneiderman; Designing the User Interface , Addison Wesley 2000 (Indian Reprint)
3.	Preece, J., Rogers, Y., & Sharp, H. (2015). Interaction design: Beyond human-computer interaction (4th ed.) John Wiley & Sons Ltd. 
4.	Yvonne Rogers, Helen Sharp, Jenny Preece, Interaction Design: Beyond Human Computer Interaction, 3rd Edition, Wiley, 2011

