* <<<PE504>>> NATURAL LANGUAGE PROCESSING
:properties:
:author: Dr. D. THenmozhi and Mr. B. Senthil Kumar
:date: 
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** COURSE OBJECTIVES
- To learn the language models.
- To understand the levels of knowledge in language processing.
- To understand the NLP applications. 

{{{unit}}}
|UNIT I |OVERVIEW AND LANGUAGE MODELING|8| 
Origins and challenges of NLP -- Knowledge in language processing --
NLP applications; Language Modeling: Language and grammar --
Grammar-based language models -- Lexical functional grammar --
Government and binding; Statistical Language Model: N-gram model --
Smoothing techniques.

{{{unit}}}
| UNIT II | WORD LEVEL AND SYNTACTIC ANALYSIS | 9 |
Word Level Analysis: Regular expressions -- Survey of morphology --
Word and sentence tokenization -- Stemmer -- Word classes --
Part-of-Speech Tagging: HMM POS tagging; Syntactic Analysis:
Constituency -- Context-free grammar -- Dependency Grammar; Parsing:
Top-down -- Bottom-up -- Ambiguity -- Early algorithm -- CYK --
Probabilistic CFG -- Probabilistic CYK parsing; Tree banks.

{{{unit}}}
| UNIT III | SEMANTIC ANALYSIS AND DISCOURSE PROCESSING | 10 |
The representation of Meaning: Meaning representation -- Computational
desiderata for representation; Lexical Semantics: word senses --
relations -- WordNet; Word Sense Disambiguation: Dictionary-based --
Supervised -- Minimally-supervised -- Word Similarity: thesaurus
methods -- distributional methods; Discourse Processing: Reference
resolution -- Anaphora resolution algorithms -- Co-reference
resolution.

{{{unit}}}
| UNIT IV | MACHINE TRANSLATION, IR AND IE | 9 |
Machine Translation(MT): Problems in machine translation -- Classical
MT -- Statistical MT; Information Retrieval: The vector space model --
Term weighting -- Evaluation of IR; Information Extraction: Named
entity recognition -- Relation detection and classification.

{{{unit}}}
| UNIT V | QUESTION ANSWERING AND SUMMARIZATION | 9 |
Factoid Question Answering: Question Processing -- Passage Retrieval
-- Answer Processing -- Evaluation of Factoid Answers; Summarization:
Content selection -- Information ordering -- Sentence realization --
Multi-Document Summarization -- Summarization Evaluation.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon the completion of the course the students should be able to: 
- Describe the language models (K2)
- Explain levels of knowledge in language processing (K2)
- Apply computational methods in semantic and discourse processing (K3)
- Apply NLP techniques to MT, IR, IE, QA and Summarization systems (K3)
- Apply evaluation metrics for different NLP applications (K3)

** TEXT BOOKS
1. Daniel Jurafsky and James H Martin, ``Speech and Language
   Processing: An introduction to Natural Language Processing,
   Computational Linguistics and Speech Recognition'', 2nd Edition,
   Prentice Hall, 2008.
2. Tanveer Siddiqui, U.S. Tiwary, ``Natural Language Processing and
   Information Retrieval'', Oxford University Press, 2008.

** REFERENCES
1. Christopher D. Manning, Hinrich Schutze, ``Foundations of
   Statistical Natural Language Processing'', MIT Press, 1999.
2. Nitin Indurkhya, Fred J. Damerau, ``Handbook of Natural Language
   Processing'', 2nd Edition, CRC Press, 2010.
3. Steven Bird, Ewan Klein, ``Natural Language Processing with
   Python'', O'Reilly Media, 2009.
4. Ruslan Mitkov, ``The Oxford Handbook of Computational
   Linguistics'', Oxford University Press, 2009.
5. NLTK -- Natural Language Tool Kit - http://www.nltk.org/.

